### ISSUE TITLE
Run summary does not include tables

### ISSUE THREAD

**Issue by seangtkelley** [wandb/client#711] opened 2019-12-11 23:12 UTC
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.18
* Python version: 3.6.9
* Operating System: Linux (Google Colab)

### Description

I want to do an analysis of data that was added to tables in my run summary. However, when I try to retrieve the data tables using the Python API, I get empty dictionaries.

### What I Did

```py
import wandb
api = wandb.Api()
run = api.run("<project id here>")

assert 'table name' in run.summary.keys() # true

run.summary['table name'] # {}
```

**Comment by lukas** [comment] 2019-12-26 17:17
I'm having trouble replicating - if your project is public or can be made public could you post a link to it?

**Comment by seangtkelley** [comment] 2020-01-09 02:57
Here is the link to the run we were attempting to retrieve the table from: https://app.wandb.ai/bertandernie/CodeSearchNet/runs/0d49hj25

However, it appears that W&B won't allow me to make it public.

**Comment by vanpelt** [comment] 2020-01-09 22:26
Thanks for the response!  I was able to reproduce the bug.  If you call `run.summary_metrcs['table name']` the data is returned, we'll look into the root cause and get a fix in the next release.

**Comment by ariG23498** [comment] 2020-12-03 04:42
Hey @seangtkelley 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Closed by ariG23498** 2020-12-03 04:42 UTC
