### ISSUE TITLE
Issue logging seaborn / plt plot via wandb.log()

### ISSUE THREAD

**Issue by harritaylor** [wandb/client#1608] opened 2020-12-11 23:52 UTC
**Describe the bug**

When I attempt to log a seaborn scatterplot to weights and biases I get the following error:
````
*** AttributeError: 'XAxis' object has no attribute '_gridOnMajor'
````

**To Reproduce**

```python
tips = sns.load_dataset("tips")
fig, ax = plt.subplots(figsize=(11.7, 8.27))
sns.scatterplot(data=tips, x="total_bill", y="tip")
wandb.log({"test_plot": fig})
# or
wandb.log({"test_plot": plt})
```

**Expected behavior**

Logging the plot to wandb interface in plotly format

**Operating System**
 - OS: MacOS
 - Browser: Chrome

**Additional context**
This seems to be happening with the example given [here](https://www.kaggle.com/lavanyashukla01/visualize-model-predictions-with-w-b) too.

**Comment by ariG23498** [comment] 2020-12-12 01:54
Hey @harritaylor 
I tried reproducing the error, but everything checks out fine for me.
## Code
```python
import seaborn as sns
import matplotlib.pyplot as plt
import wandb

with wandb.init(entity="xxx", project="xxx") as run:
  tips = sns.load_dataset("tips")
  fig, ax = plt.subplots(figsize=(11.7, 8.27))
  sns.scatterplot(data=tips, x="total_bill", y="tip")
  wandb.log({"plot":fig})
```

## Screenshot
![image](https://user-images.githubusercontent.com/36856589/101969565-eb6d7e00-3c4a-11eb-9c51-1bd580842242.png)

Hope this helps.

**Comment by ariG23498** [comment] 2020-12-15 03:04
Hey @harritaylor 
We are closing this issue as of now.
Please feel free to open this if the issue persists. :smile:

**Closed by ariG23498** 2020-12-15 03:04 UTC
Labels: bug

**Comment by harritaylor** [comment] 2020-12-16 11:29
@ariG23498 thanks for getting back to me, apologies I didn't reply sooner - I only got back to work today.
I think it was something to do with my environment -- with a fresh conda env it works fine. Sorry!

**Comment by Asap7772** [comment] 2021-04-21 22:44
I had an issue like this because my matplotlib and plotly version is incorrect:

In particular I hit this bug when using the following versions of matplotlib/plotly versions.
matplotlib>=3.3.3
plotly>=4.12.0

**Comment by chanmi168** [comment] 2021-06-26 16:27
@harritaylor Do you mind sharing your matplotlib and plotly versions? Thank you!

**Comment by abcde-1447** [comment] 2021-07-09 02:29
Hi @harritaylor @chanmi168 I got the same issue, can you share your matplotlib and plotly versions?  Thanks!

**Comment by abcde-1447** [comment] 2021-07-09 02:37
@chanmi168 FYI I fixed this issue with following versions:

matplotlib == '3.3.3'
plotly == '5.1.0'

Hope it helps.

**Comment by chanmi168** [comment] 2021-07-09 03:14
@abcde-1447 
Thanks so much!
