### ISSUE TITLE
No message when resuming a run from id

### ISSUE THREAD

**Issue by umgupta** [wandb/client#476] opened 2019-08-13 01:31 UTC
Currently, when resuming a run, there is no message or notification on terminal logs that it is restarting. I would prefer to have this because one could make a typo in id and not realize.

**Comment by vanpelt** [comment] 2019-08-14 01:31
Thanks @umgupta, are you running from jupyter or directly from a terminal?  I thought we had a message in the terminal, but we may have regressed.

**Comment by umgupta** [comment] 2019-08-14 01:37
I m running from terminal. But I will check it again and get back on this.

**Comment by umgupta** [comment] 2019-08-19 22:33
I checked with below setup and it doesn't print the resume information. 
Attached is the screenshot (first line is the message of custom config that I have written)  
```
wandb, version 0.8.8
Python 3.7.3
Linux
```
![Screenshot from 2019-08-18 19-12-12](https://user-images.githubusercontent.com/4678394/63304062-960f9f80-c296-11e9-95ef-7942b52dd754.png)

**Comment by ariG23498** [comment] 2020-12-02 05:12
Hey @umgupta 
Could you check if the issue is resolved with the newest version of wandb (0.10.11)

Due to the inactivity of the thread we would like to close it if the issue is resolved :smiley:

**Comment by ariG23498** [comment] 2020-12-03 03:51
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Closed by ariG23498** 2020-12-03 03:51 UTC
Labels: enhancement
