### ISSUE TITLE
wandb: Network error (TransientException), entering retry loop. 

### ISSUE THREAD

**Issue by siarez** [wandb/client#805] opened 2020-01-28 21:00 UTC
wandb, version 0.8.22
Python 3.6.8
Ubuntu 18

### Description

W&B was working fine until one day I started getting these error messages. I'm using W&B normally as far as I can tell. I'm not using sweeps or anything fancy. I "init" and then "log":
```
wandb: Tracking run with wandb version 0.8.22
wandb: Run data is saved locally in XXX/wandb/run-20200128_181440-yz2o7uiw
wandb: Syncing run A002
wandb: ⭐ View project at https://app.wandb.ai/XXX
wandb: 🚀 View run at https://app.wandb.ai/XXX
wandb: Run `wandb off` to turn off syncing.

wandb: Network error (TransientException), entering retry loop. See /home/XXX/wandb/debug.log for full traceback.
wandb: ERROR Error uploading "___batch_archive_1.tgz": CommError, None
[ batch loss: 0.000208 | batch RMSE: 3.7270] :  27%|███████████▋                               | 36/132 [00:28<01:17,  1.24it/sBus error (core dumped) 2.6732 | val-loss: 0.000312| val_rmse: 4.0230:  74%|█████████████▎    | 37/50 [1:07:44<23:51, 110.11s/it]
(sia-env) XXX:~/projects/orofacial$ wandb: Program ended successfully.        | 14/132 [00:10<01:34,  1.25it/s]
wandb: Run summary:
wandb:                       _step 73
wandb:                  _timestamp 1580239346.2581983
wandb:                    _runtime 4074.0023016929626
wandb:                        Loss 0.00013416090676909802
wandb:               learning rate 1.25e-06
wandb: Syncing 8 W&B file(s) and 0 media file(s)
 (%(failed_batches)d failed uploads)wandb: Network error (TransientException), entering retry loop. See /home/siarez/projects/orofacial/artifacts/train.py/2020-01-28-13-14-32_0/wandb/debug.log for full traceback.
 (%(failed_batches)d failed uploads)wandb: ERROR Error uploading "config.yaml": CommError, None
 (%(failed_batches)d failed uploads)wandb: ERROR Error uploading "wandb-summary.json": CommError, None
wandb: ERROR Error uploading "wandb-metadata.json": CommError, None
 (%(failed_batches)d failed uploads)wandb: ERROR Error uploading "output.log": CommError, None
 (%(failed_batches)d failed uploads)wandb:                                                                                
wandb: Synced A002: https://app.wandb.ai/siarez/orofacial/runs/yz2o7uiw
```

### What I Did
Nothing

The `debug.log` was too large to fit in "pastebin". But here are the first 140 lines: https://hastebin.com/ixonizoyal.sql

Here are the last 170 lines of `debug.log`:  https://hastebin.com/alevotuduv.sql

**Comment by syorami** [comment] 2020-07-04 07:12
I'm having the same problem. Did you figure out the solution?

**Comment by vanpelt** [comment] 2020-07-04 19:13
@syorami you may be getting rate limited.  Can you share the file `wandb/debug.log` and what version of the python library you're using?

**Comment by syorami** [comment] 2020-07-05 02:04
I'm using python=3.6.8 wandb=0.9.2. The log file is large and here is part of it:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/user/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/user/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/user/anaconda3/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/user/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/user/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/user/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/home/user/anaconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/user/anaconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/user/anaconda3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

`wandb sync` gives this error:

```
wandb: Network error (ConnectionError), entering retry loop. See /home/user/Documents/syoya/Competes/Alaska2/wandb/debug.log for full traceback.
wandb: Network error (ConnectionError), entering retry loop. See /home/user/Documents/syoya/Competes/Alaska2/wandb/debug.log for full traceback.
```

**Comment by syorami** [comment] 2020-07-05 02:06
@vanpelt Actually I found that this uploading file is requesting the minio service at port 9000. So I ran `wandb local -p 9000` and uploading works.

**Comment by vanpelt** [comment] 2020-07-06 16:20
What version of `wandb/local` are you running, you can find out at `/system-admin`?  `wandb/local:0.9.19` should have a fix for this issue.

**Comment by hongliny** [comment] 2020-07-15 23:03
> @syorami you may be getting rate limited. Can you share the file `wandb/debug.log` and what version of the python library you're using?

Is wandb/local also subject to rate limits?

**Comment by vanpelt** [comment] 2020-07-15 23:57
There are default limits implemented in local to avoid overwhelming the server.  They are very high, I believe 200 requests per API key, per second.

**Comment by syorami** [comment] 2020-08-01 15:40
> What version of `wandb/local` are you running, you can find out at `/system-admin`? `wandb/local:0.9.19` should have a fix for this issue.

Sorry for the late reply. I'm now not using the latest version but 0.9.18 and it works fine.

**Comment by ariG23498** [comment] 2020-12-03 05:04
Hey @syorami 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing this issue as there is a fix to it (as you mentioned). Please comment to reopen.

**Closed by ariG23498** 2020-12-03 05:04 UTC
Labels: c:sync

**Comment by laurelrr** [comment] 2021-03-02 21:30
This is an issue for me.  I am on Windows 10 - wsl2 running Ubuntu 18.04
python version 3.8.5
wandb, version 0.10.21

The very first time I tried running yolov5 with wandb, it worked.  But it has not worked again since then.  I've run the 
`wandb login --relogin`
and the key is appeneded to the netrc file.  

I'm training custom data with the following command (output follows):

`$ python train.py --img 1260 --batch 16 --epochs 5 --data testYolov5.yaml --weights yolov5s.pt`
github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 v4.0-111-gab86cec torch 1.7.1 CPU

Namespace(adam=False, batch_size=16, bucket='', cache_images=False, cfg='', data='./data/testYolov5.yaml', device='', entity=None, epochs=5, evolve=False, exist_ok=False, global_rank=-1, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[1260, 1260], linear_lr=False, local_rank=-1, log_artifacts=False, log_imgs=16, multi_scale=False, name='exp', noautoanchor=False, nosave=False, notest=False, project='runs/train', quad=False, rect=False, resume=False, save_dir='runs/train/exp11', single_cls=False, sync_bn=False, total_batch_size=16, weights='yolov5s.pt', workers=8, world_size=1)
Start Tensorboard with "tensorboard --logdir runs/train", view at http://localhost:6006/
hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0
Overriding model.yaml nc=80 with nc=2

                 from  n    params  module                                  arguments
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     18816  models.common.C3                        [64, 64, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  1    156928  models.common.C3                        [128, 128, 3]
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  6                -1  1    625152  models.common.C3                        [256, 256, 3]
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]
  9                -1  1   1182720  models.common.C3                        [512, 512, 1, False]
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]
 24      [17, 20, 23]  1     18879  models.yolo.Detect                      [2, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 283 layers, 7066239 parameters, 7066239 gradients, 16.4 GFLOPS

Transferred 356/362 items from yolov5s.pt
Scaled weight_decay = 0.0005
Optimizer groups: 62 .bias, 62 conv.weight, 59 other
wandb: W&B API key is configured (use `wandb login --relogin` to force relogin)
wandb: Network error (ReadTimeout), entering retry loop. See wandb/debug-internal.log for full traceback.
wandb: Network error (ReadTimeout), entering retry loop. See wandb/debug-internal.log for full traceback.

I've tried uninstalling and re-installing wandb.  
I also don't seem to be able to complete a run without wandb installed.
I'm not sure what else to try.

**Comment by laurelrr** [comment] 2021-03-02 21:34
Here's the debug.log file

`$ cat wandb/debug.log`
2021-03-02 13:17:36,088 INFO    MainThread:30017 [wandb_setup.py:_flush():69] setting env: {}
2021-03-02 13:17:36,088 INFO    MainThread:30017 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-02 13:17:36,089 INFO    MainThread:30017 [wandb_init.py:_log_setup():334] Logging user logs to /mnt/c/users/Laurel/Documents/GitHub/yolov5/wandb/run-20210302_131735-2bxcbm7t/logs/debug.log
2021-03-02 13:17:36,090 INFO    MainThread:30017 [wandb_init.py:_log_setup():335] Logging internal logs to /mnt/c/users/Laurel/Documents/GitHub/yolov5/wandb/run-20210302_131735-2bxcbm7t/logs/debug-internal.log
2021-03-02 13:17:36,091 INFO    MainThread:30017 [wandb_init.py:init():367] calling init triggers
2021-03-02 13:17:36,092 INFO    MainThread:30017 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {'weights': 'yolov5s.pt', 'cfg': '', 'data': './data/testYolov5.yaml', 'hyp': {'lr0': 0.01, 'lrf': 0.2, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0}, 'epochs': 5, 'batch_size': 16, 'img_size': [1260, 1260], 'rect': False, 'resume': False, 'nosave': False, 'notest': False, 'noautoanchor': False, 'evolve': False, 'bucket': '', 'cache_images': False, 'image_weights': False, 'device': '', 'multi_scale': False, 'single_cls': False, 'adam': False, 'sync_bn': False, 'local_rank': -1, 'log_imgs': 16, 'log_artifacts': False, 'workers': 8, 'project': 'runs/train', 'entity': None, 'name': 'exp', 'exist_ok': False, 'quad': False, 'linear_lr': False, 'world_size': 1, 'global_rank': -1, 'save_dir': 'runs/train/exp11', 'total_batch_size': 16}
2021-03-02 13:17:36,093 INFO    MainThread:30017 [wandb_init.py:init():416] starting backend
2021-03-02 13:17:36,093 INFO    MainThread:30017 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-03-02 13:17:36,111 INFO    MainThread:30017 [backend.py:ensure_launched():123] starting backend process...
2021-03-02 13:17:36,116 INFO    MainThread:30017 [backend.py:ensure_launched():127] started backend process with pid: 30137
2021-03-02 13:17:36,119 INFO    MainThread:30017 [wandb_init.py:init():421] backend started and connected
2021-03-02 13:17:36,156 INFO    MainThread:30017 [wandb_init.py:init():461] updated telemetry
2021-03-02 13:17:36,157 INFO    MainThread:30017 [wandb_init.py:init():480] communicating current version
2021-03-02 13:17:37,115 INFO    MainThread:30017 [wandb_init.py:init():485] got version response
2021-03-02 13:17:37,116 INFO    MainThread:30017 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-03-02 13:18:05,202 ERROR   Thread-2  :30017 [retry.py:__call__():111] Retry attempt failed:
Traceback (most recent call last):
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1106: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/urllib3/connectionpool.py", line 385, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 123, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)
2021-03-02 13:18:07,120 INFO    MainThread:30017 [interface.py:_communicate_run():635] couldn't get run from backend
2021-03-02 13:18:07,123 ERROR   MainThread:30017 [wandb_init.py:init():497] backend process timed out
2021-03-02 13:18:07,124 ERROR   MainThread:30017 [wandb_init.py:init():506] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-03-02 13:20:49,677 WARNING MainThread:30017 [wandb_init.py:init():763] interrupted
Traceback (most recent call last):
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 743, in init
    run = wi.init()
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 509, in init
    backend.cleanup()
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 155, in cleanup
    self.wandb_process.join()
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/laurel/miniconda3/envs/yolov5/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

**Comment by vanpelt** [comment] 2021-03-02 22:33
Hey @siarez the instance your running this on either can't communicate with the internet, or is behind a proxy that making the SSL handshake fail.  You can run the script in offline mode and later sync the data to a wandb server from a machine that has functioning internet.  Just set the `WANDB_MODE=offline` environment variable or specify `mode="offline"` in your call to `wandb.init`

**Comment by yhy-2000** [comment] 2021-04-30 06:53
I met the same problem, but just after a few minutes, it began work. (But dont forget to use "wandb login" first)

I guess maybe it is a problem caused by net speed.

**Comment by jw3126** [comment] 2021-05-07 06:31
I get the same error message, not sure if the cause is related. In use wandb 0.10.29 + Python 3.6.9 local and it mostly works fine. Only when I try to log media (matplotlib plots) I get 
`wandb: Network error (TransientException), entering retry loop.`
and plots don't show up in the browser. All other like charts do show up.

**Comment by vanpelt** [comment] 2021-05-07 16:59
Hey @jw3126 can you are a colab or the actual code that is causing this for you?

**Comment by jw3126** [comment] 2021-05-07 18:19
I will try to produce a mwe.
