### ISSUE TITLE
"failed to launch"

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#737] opened 2020-01-04 02:06 UTC
My training run crashes with the following
```
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb/debug.log
```

This is on a fresh p3.16xlarge instance, using "Deep Learning AMI (Ubuntu 18.04) Version 26.0" and pytorch_p36 environment.

Some logs below. Is there some way to have this failure be a warning and not crash my main Python process?

```
create web directory ./checkpoints/spade_cityscapes_dev/web...
wandb: Tracking run with wandb version 0.8.19
wandb: ERROR W&B process (PID 4087) did not respond
wandb: ERROR W&B process failed to launch, see: wandb/debug.log
Traceback (most recent call last):
  File "train.py", line 38, in <module>
    name='base',
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/wandb/__init__.py", line 1067, in init
    _init_headless(run)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/wandb/__init__.py", line 296, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
```
debug.log

```
2020-01-04 02:02:26,592 DEBUG   MainThread:4087 [wandb_config.py:_load_defaults():110] no defaults not found in config-defaults.yaml
2020-01-04 02:02:26,604 DEBUG   MainThread:4087 [cmd.py:execute():728] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/ubuntu, universal_newlines=False, shell=None, istream=<valid stream>)
2020-01-04 02:02:26,611 DEBUG   MainThread:4087 [cmd.py:execute():728] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/ubuntu, universal_newlines=False, shell=None, istream=None)
2020-01-04 02:02:26,615 DEBUG   MainThread:4087 [cmd.py:execute():728] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=/home/ubuntu, universal_newlines=False, shell=None, istream=None)
```

**Comment by yaroslavvb** [comment] 2020-01-04 03:28
Somehow this seems connected to directory I'm launching the script from, in one directory wandb.init() works, but when running from another directory it crashes. Deleting ./wandb didn't make difference.

**Comment by vanpelt** [comment] 2020-01-04 05:51
I think it’s related to git.  Can you run git status from each directory and see if one hangs for a while?

**Comment by yaroslavvb** [comment] 2020-01-04 06:26
Aha, that's it.

After deleting .git directory, it works as expected. "git status" doesn't hang, but it does take longer than usual (5 seconds)

**Comment by vanpelt** [comment] 2020-01-04 20:17
Yeah, we already handle some hanging git commands, but we're clearly missing something.  If you can send me a zip of the folder with the .git directory in it that causes it we can ensure we just handle this case.  If the code is sensitive, we can probably reproduce manually.

**Comment by yaroslavvb** [comment] 2020-01-06 22:40
I deleted the folder, however I imagine it could've been in a bad state -- I rsync .git folder from local machine where I do the code editing to remote machine where I do the running, so this could've been a one-off error of .git folder being corrupted

**Comment by yaroslavvb** [comment] 2020-01-07 01:11
Got another failing issue like this, will send .git in email

**Comment by yaroslavvb** [comment] 2020-01-07 01:12
Couldn't find work email, sent it to vanpelt gmail

**Comment by vanpelt** [comment] 2020-01-07 01:28
Thanks! vanpelt@wandb.com works for next time.

**Comment by yaroslavvb** [comment] 2020-01-09 02:30
Another instance I saw recently. 
```
(pytorch_p36) yaroslavvb@sixteen:~/SPADE$ python train.py --name spade_cityscapes --dataset_mode cityscapes --dataroot ~/lab/datasets/cityscapes --batchSize 16 --gpu_ids=0,1,2,3,4,5,6,7
wandb: Tracking run with wandb version 0.8.19
wandb: ERROR W&B process (PID 19758) did not respond
wandb: ERROR Failed to kill wandb process, PID 19758
wandb: ERROR W&B process failed to launch, see: /tmp/wandb-debug.log
Traceback (most recent call last):
  File "train.py", line 15, in <module>
    sync_tensorboard=True,
  File "/home/yaroslavvb/.conda/envs/pytorch_p36/lib/python3.7/site-packages/wandb/__init__.py", line 1067, in init
    _init_headless(run)
  File "/home/yaroslavvb/.conda/envs/pytorch_p36/lib/python3.7/site-packages/wandb/__init__.py", line 296, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
wandb.run_manager.LaunchError: W&B process failed to launch, see: /tmp/wandb-debug.log
(pytorch_p36) yaroslavvb@sixteen:~/SPADE$ cat /tmp/wandb-debug.log
cat: /tmp/wandb-debug.log: No such file or directory
```

Tried deleting `wandb`, `.git` and `../.git`, still fails. Tried 15 minutes later, it works again.

**Comment by raubitsj** [comment] 2020-02-05 19:18
In 0.8.25 we have added some protections that should prevent this.  The most common case is that the git repo either has many untracked files (usually when the training set is in the same location), or there is other .git corruption.

Currently these protections are for non-windows and non-jupyter environments.  Closing this bug by duping it to a catchall issue regarding launch errors.  If you still see this problem and do not think it is related to the duplicated bug, please reopen.  Otherwise please add new reports to:
https://github.com/wandb/client/issues/839

**Comment by raubitsj** [comment] 2020-02-05 19:21
Duplicate of #839

**Closed** 2020-02-05 19:21 UTC
Labels: bug
