### ISSUE TITLE
wandb.watch doesn't work with modules that return dicts

### ISSUE THREAD

**Issue by douglasrizzo** [wandb/client#1122] opened 2020-06-28 05:06 UTC
`wandb --version && python --version && uname`

* Weights and Biases version: 0.9.1
* Python version: 3.7.7
* Operating System: Manjaro Linux 20.0.3

### Description

When I use `wandb.watch(model)` in a model of mine, I get a `StopIteration` message and my program crashes. When I comment that line out, everything works fine.

Two things my model does that could be considered non-standard are the use of some neural network layers from PyTorch Geometric and the output of a dictionary instead of a tensor. In the traceback I provide below, the error occurs exactly in a layer that returns a dict, so I believe the dict is the culprit.

### What I Did

```
Traceback (most recent call last):
  File "/home/dodo/Code/dodonet/dodonet/training/run.py", line 434, in <module>
    OffPolicySMACRunner(trainer).run()
  File "/home/dodo/Code/dodonet/dodonet/training/run.py", line 109, in run
    output_dict = self.model.policy_net(current_state)
  File "/home/dodo/.anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dodo/Code/dodonet/dodonet/nn/nets.py", line 215, in forward
    xdict = self.action_layer(obs_by_class, enc_node_types)
  File "/home/dodo/.anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 559, in __call__
    var = next((v for v in var.values() if isinstance(v, torch.Tensor)))
StopIteration
```

**Comment by indigoviolet** [comment] 2020-07-02 05:37
Confirmed. This also happens with Detectron2, which returns a custom `Instances` object. Here's a stacktrace for that: https://gist.github.com/indigoviolet/ea3eb79b9493abc4b31a4c0a91519b92 , which can be reproed using the Detectron2 colab tutorial. I can share my Colab notebook if that's useful.

**Comment by vanpelt** [comment] 2020-07-02 05:52
@indigoviolet a colab would be really useful.  You can share it with `vanpelt@wandb.com`

**Comment by douglasrizzo** [comment] 2020-07-02 07:14
I made two colabs with stuff that was originally in my model (the one that failed). Unfortunately, I couldn't reproduce the error I had, as in both of them, `wandb.watch()` worked correctly.

- In [this one](https://gist.github.com/douglasrizzo/81b9b2a190cf5ad3125e929df919e98d), I tested a simple network that outputs a dictionary and another one that has a fork in the architecture (2 final fully-connected layers that compose the final output together).
- In [this one](https://gist.github.com/douglasrizzo/1418883a8779563967bea80ef699d2a9), I tested one of the PyTorch Geometric tutorials.

**Comment by indigoviolet** [comment] 2020-07-03 01:35
> @indigoviolet a colab would be really useful. You can share it with `vanpelt@wandb.com`

@vanpelt : Here's the [colab](https://colab.research.google.com/drive/1thq6pzM-FDMzHaY5gSxmT_jaT3KcEaSA?usp=sharing).

The error happens in the `Train on a custom dataset > Train!` section, you'll have to execute the `Install Detectron2` section to install required packages.

**Comment by YKX-A** [comment] 2020-12-06 02:56
The same problem when my network return **an empty dict** `{}`, but ok when there is at least one content in the dict!

**Comment by kexinhuang12345** [comment] 2021-01-05 01:34
Hi, I also encountered this problem, is there a workaround for that?

**Comment by cola-nicolas** [comment] 2021-04-05 01:25
Any update on this issue ? I'm having the same problem, and I can't find a workaround

**Comment by cola-nicolas** [comment] 2021-04-12 02:39
Note that when I meet this problem, I also receive the following warning :

>/home/user/miniconda3/envs/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py:795: **UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.**

---

If I comment the line `wandb.watch(agent)`, I don't have this warning.

**Comment by vanpelt** [comment] 2021-04-12 06:06
@cola-nicolas can you share the traceback you're getting?

**Comment by cola-nicolas** [comment] 2021-04-12 06:11
@vanpelt 

>**UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions**. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
>
>  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
Traceback (most recent call last):
  File "main.py", line 53, in <module>
    main()
  File "main.py", line 43, in main
    trainer.run()
  File "/home/remondn/workspace/parka/parka/trainer.py", line 145, in run
    logs = self.train_step(batch_data)
  File "/home/remondn/workspace/parka/parka/trainer.py", line 35, in train_step
    log_probs, critics, rewards, masks = self.run_episode(data)
  File "/home/remondn/workspace/parka/parka/trainer.py", line 66, in run_episode
    actions, log_p, critic = self.agent(**inputs, sample=sample)
  File "/home/remondn/miniconda3/envs/parka/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/remondn/workspace/parka/parka/agent.py", line 81, in forward
    actions, log_prob = self.actions_head(state_repr, cls_repr, coord_ids, type_ids, sample=sample)
  File "/home/remondn/miniconda3/envs/parka/lib/python3.6/site-packages/torch/nn/modules/module.py", line 905, in _call_impl
    var = next((v for v in var.values() if isinstance(v, torch.Tensor)))
**StopIteration**

---

I tried to make a minimal reproducible example, but couldn't reproduce so far. I will keep trying and update the issue if I'm successful...

**Comment by cola-nicolas** [comment] 2021-04-16 00:35
@vanpelt 
I finally could reproduce the error with a minimal example !!

Please run the following Colab : https://colab.research.google.com/drive/180DN6nFDs0QYDbZkTAx8j5Bd3tUXO4KD?usp=sharing

---

The error appears when a module returning a `dict` is wrapped in a custom module.

---

Error on Colab :

```
wandb: W&B syncing is set to `offline` in this directory.  Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-5-bce620ab122e> in <module>()
     13 
     14 input = torch.randint(16, [8, 5])
---> 15 output = model(input)
     16 out = (output["key"]["emb1"]).sum(-1)
     17 loss = F.mse_loss(out, input.float())

2 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

<ipython-input-2-a5b197d5e9c8> in forward(self, *args, **kwargs)
      5 
      6     def forward(self, *args, **kwargs):
----> 7         return self.emb(*args, **kwargs)

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    903             while not isinstance(var, torch.Tensor):
    904                 if isinstance(var, dict):
--> 905                     var = next((v for v in var.values() if isinstance(v, torch.Tensor)))
    906                 else:
    907                     var = var[0]

StopIteration: 
```

**Comment by vanpelt** [comment] 2021-04-16 03:14
@cola-nicolas Thanks so much for the repro!  I was able to implement a fix in the PR listed above.  If you want to try it yourself you can install wandb with:

```
pip install --upgrade git+git://github.com/wandb/client.git@bug/issue-1122#egg=wandb
```

This should make it into the next release likely early next week.

**Comment by cola-nicolas** [comment] 2021-04-16 06:03
@vanpelt Wow so fast ! 🥇 
Thanks for the fix !

**Comment by cola-nicolas** [comment] 2021-04-20 00:14
@vanpelt  @douglasrizzo 
Issue is fixed in the latest release (`0.10.27`). We can close this issue.

**Comment by vanpelt** [comment] 2021-04-20 00:20
@cola-nicolas we decided to wait one more week to officially release this as it broke some of our regression tests that were using older version of torch.  I'll update this thread with a new branch that can be used until the official release.

**Comment by raubitsj** [comment] 2021-04-20 01:01
@cola-nicolas the new branch for this fix can be installed with:
```
pip install --upgrade git+git://github.com/wandb/client.git@bug/issue-1122-2#egg=wandb
```

**Closed** 2021-12-30 19:03 UTC
Labels: bug
