### ISSUE TITLE
[CLI] Video logging issues with OpenAI Gym

### ISSUE THREAD

**Issue by MauricioSalazare** [wandb/client#2743] opened 2021-10-07 18:04 UTC
**Description**
The .mp4 videos recorded by the VideoRecorder() objects in OpenAI do not show up on the wandb.ai dashboard.

**Wandb features**
I am using wandb for a single run.

**How to reproduce**
This is the minimum code to reproduce
```python
import gym
import numpy as np
import wandb
from tqdm import tqdm
from gym.wrappers.monitoring.video_recorder import VideoRecorder

wandb.login()
wandb.init(project='CartPole_buggy', entity='yourentity')
np.random.seed(123)
env = gym.make('CartPole-v1')

EPISODES = 100
recorded_every = 10

enable_recording = False
for iteration in tqdm(range(EPISODES)):
    if iteration % recorded_every == 0:
        enable_recording = True
        video_path = f"./video_bug/video_{iteration}.mp4"
        video_recorder = VideoRecorder(env, video_path, enabled=True)

    state = env.reset()
    done = False
    rewards = []
    while not done:
        if enable_recording:
            env.unwrapped.render()
            video_recorder.capture_frame()

        action = env.action_space.sample()
        next_state, reward, done, info = env.step(action)
        rewards.append(reward)

    if enable_recording:
        # Save the video in wandb and close the recorder
        wandb.log({'video': wandb.Video(video_path, fps=4, format="mp4")}, commit=False)
        video_recorder.close()
        enable_recording = False
    wandb.log({"reward": np.sum(rewards)})

env.close()
wandb.finish()
```

**Environment**
- OS: Windows 10 (20H2)
- Environment: conda 4.10.3
- Python Version: 3.8.10
-gym==0.19.0
-wandb==0.12.1

**Workaround**
After some digging, it seems that the video codec used by ffmpeg backend on windows is "mpeg4" and it is not allowing to show the videos on wandb. This is probably related to the issue [#2412](https://github.com/openai/gym/issues/2412) on OpenAI Gym.
This can probably give some more light for the reasons of the wandb issues [#2143](https://github.com/wandb/client/issues/2143), and [#798](https://github.com/wandb/client/issues/798)
The workaround is to change the codec from "mpeg4" to "h264" editing the method start() of the ImageEnconder class in the video_recorder.py script on gym.
So, if you do the change and run the above script again. Everything should be fine.

 ```python
def start(self):
        if self.backend == "ffmpeg":
            self.cmdline = (
                self.backend,
                "-nostats",
                "-loglevel",
                "error",  # suppress warnings
                "-y",
                # input
                "-f",
                "rawvideo",
                "-s:v",
                "{}x{}".format(*self.wh),
                "-pix_fmt",
                ("rgb32" if self.includes_alpha else "rgb24"),
                "-r",
                "%d" % self.frames_per_sec,
                "-i",
                "-",  # this used to be /dev/stdin, which is not Windows-friendly
                # output
                "-an",
                "-r",
                "%d" % self.frames_per_sec,
                "-vcodec",
                "mpeg4",  # <--------- Change this for "h264"
                "-pix_fmt",
                "bgr24",
                "-r",
                "%d" % self.output_frames_per_sec,
                self.output_path,
            )
```
Can wandb support the default codec if the problem is not solved by the OpenAI gym?

Thanks for your support. You have an amazing product here! I enjoy working with wandb.

Cheers,
Mauricio.

**Comment by vanpelt** [comment] 2021-10-07 21:33
Thanks @MauricioSalazare this is actual a limitation of [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=54036).  Likely due to licensing issues.  In the future it's possible we could run a transcoding server to convert videos logged in non-web friendly formats but it's not currently a priority on our roadmap.  I'll keep this issue open as it will definitely be helpful to other users.  It would also likely be a good idea to file a separate issue or PR in the gym repo as it probably makes more sense to default to h264 unless the OpenAI team has good reasons not to.

**Comment by ellisbrown** [comment] 2021-11-30 22:38
@MauricioSalazare 
> I agree that this issue will probably help others. At least it will give some guidance for someone who sees the grey box in wandb/chrome without a video :).

I've been searching around for a while about this, and just stumbled upon this. I opened in Safari and it works as expected! Thanks a ton for raising the issue and saving my sanity.

**Comment by vwxyzjn** [comment] 2022-02-19 22:11
Hey, so I can confirm this works for the latest release 0.22.0.

See https://wandb.ai/costa-huang/cleanRL/runs/2d3p8kvi

![image](https://user-images.githubusercontent.com/5555347/154820780-78025856-6bd9-4711-a7bc-12ceacc26bcc.png)

This should close the issue.

**Closed** 2022-05-09 22:13 UTC
Labels: cli

**Comment by Jackory** [comment] 2022-09-09 05:38
> h264
I have encountered this problem, too. Your solution works for me, thanks!

**Comment by Jackory** [comment] 2022-09-09 05:39
> **Description** The .mp4 videos recorded by the VideoRecorder() objects in OpenAI do not show up on the wandb.ai dashboard.
> 
> **Wandb features** I am using wandb for a single run.
> 
> **How to reproduce** This is the minimum code to reproduce
> 
> ```python
> import gym
> import numpy as np
> import wandb
> from tqdm import tqdm
> from gym.wrappers.monitoring.video_recorder import VideoRecorder
> 
> wandb.login()
> wandb.init(project='CartPole_buggy', entity='yourentity')
> np.random.seed(123)
> env = gym.make('CartPole-v1')
> 
> EPISODES = 100
> recorded_every = 10
> 
> enable_recording = False
> for iteration in tqdm(range(EPISODES)):
>     if iteration % recorded_every == 0:
>         enable_recording = True
>         video_path = f"./video_bug/video_{iteration}.mp4"
>         video_recorder = VideoRecorder(env, video_path, enabled=True)
> 
>     state = env.reset()
>     done = False
>     rewards = []
>     while not done:
>         if enable_recording:
>             env.unwrapped.render()
>             video_recorder.capture_frame()
> 
>         action = env.action_space.sample()
>         next_state, reward, done, info = env.step(action)
>         rewards.append(reward)
> 
>     if enable_recording:
>         # Save the video in wandb and close the recorder
>         wandb.log({'video': wandb.Video(video_path, fps=4, format="mp4")}, commit=False)
>         video_recorder.close()
>         enable_recording = False
>     wandb.log({"reward": np.sum(rewards)})
> 
> env.close()
> wandb.finish()
> ```
> 
> **Environment**
> 
> * OS: Windows 10 (20H2)
> * Environment: conda 4.10.3
> * Python Version: 3.8.10
>   -gym==0.19.0
>   -wandb==0.12.1
> 
> **Workaround** After some digging, it seems that the video codec used by ffmpeg backend on windows is "mpeg4" and it is not allowing to show the videos on wandb. This is probably related to the issue [#2412](https://github.com/openai/gym/issues/2412) on OpenAI Gym. This can probably give some more light for the reasons of the wandb issues [#2143](https://github.com/wandb/client/issues/2143), and [#798](https://github.com/wandb/client/issues/798) The workaround is to change the codec from "mpeg4" to "h264" editing the method start() of the ImageEnconder class in the video_recorder.py script on gym. So, if you do the change and run the above script again. Everything should be fine.
> 
> ```python
> def start(self):
>        if self.backend == "ffmpeg":
>            self.cmdline = (
>                self.backend,
>                "-nostats",
>                "-loglevel",
>                "error",  # suppress warnings
>                "-y",
>                # input
>                "-f",
>                "rawvideo",
>                "-s:v",
>                "{}x{}".format(*self.wh),
>                "-pix_fmt",
>                ("rgb32" if self.includes_alpha else "rgb24"),
>                "-r",
>                "%d" % self.frames_per_sec,
>                "-i",
>                "-",  # this used to be /dev/stdin, which is not Windows-friendly
>                # output
>                "-an",
>                "-r",
>                "%d" % self.frames_per_sec,
>                "-vcodec",
>                "mpeg4",  # <--------- Change this for "h264"
>                "-pix_fmt",
>                "bgr24",
>                "-r",
>                "%d" % self.output_frames_per_sec,
>                self.output_path,
>            )
> ```
> 
> Can wandb support the default codec if the problem is not solved by the OpenAI gym?
> 
> Thanks for your support. You have an amazing product here! I enjoy working with wandb.
> 
> Cheers, Mauricio.

I have encountered this problem, too. Your solution works for me, thanks!
