### ISSUE TITLE
Sweep is launching runs as individual runs instead of attaching them to sweep

### ISSUE THREAD

**Issue by mathemakitten** [wandb/client#749] opened 2020-01-09 16:49 UTC
* Weights and Biases version: 0.8.19
* Python version: 3.6.9
* Operating System: Linux

### Description

I'm attempting to run a sweep over hyperparameters but the jobs are launching as individual runs instead of as part of the sweep. Can you describe what conditions must hold for jobs to run as part of a sweep?
 
### What I Did

The approximate structure of my workflow is this: 

**train.py:**
* `sweep_id = wandb.sweep(sweep_config)`
* wandb.agent(sweep_id, function=train_sweep(hparams, run_config, hparams_file, sweep_config))```
where `train_sweep` is a function which calls a model definition in `model.py` as below.

**model.py**
```
class Model:
wandb.init(config=config_defaults)
config = wandb.config
update model params by referring to config.param for each param
model.train()
```

It seems that the init in model.py is starting up a new context instead of attaching to the sweep run even though it is started with the Wandb agent, how can I fix this? Is there some way for me to "pass" the correct W&B sweep context to the model class instantiation in the other file?

Also, is there a way to instantiate a sweep without manually defining the defaults? i.e. have just it pick one from the given sweep config.

**Comment by raubitsj** [comment] 2020-01-09 17:00
The sweep context should be set automatically for any wandb.init call after being initiated by an agent.  Let me look into this and give some theories of what might be happening.  Is your train_sweep function spawning a new process to train the model?

Fyi:
The config=config_defaults is only needed if you want to run the same code without being started by a sweep

**Comment by mathemakitten** [comment] 2020-01-09 17:04
Essentially yes, train_sweep is launching a new process to train a model on a TPU, and model artifacts get synced from gcloud buckets to my instance.

Thanks for the note re: config_defaults, that's good to know.

**Comment by mathemakitten** [comment] 2020-01-09 17:13
Oh I should mention, I'm getting this in the logs looping over and over again with different IDs, it looks like it's spawning a single run and then trying to do sweeps but the sweeps just aren't working.

2020-01-09 17:11:06,122 - wandb.wandb_agent - INFO - Agent received command: run
INFO:wandb.wandb_agent:Agent received command: run
2020-01-09 17:11:06,122 - wandb.wandb_agent - INFO - Agent starting run with config:
	{MYCONFIG}
INFO:wandb.wandb_agent:Agent starting run with config:
	{MYCONFIG}
/home/.../bin/python: can't find '__main__' module in ''
2020-01-09 17:11:11,151 - wandb.wandb_agent - INFO - Running runs: ['wcj68yoo']
INFO:wandb.wandb_agent:Running runs: ['wcj68yoo']
2020-01-09 17:11:11,152 - wandb.wandb_agent - INFO - Cleaning up finished run: wcj68yoo

**Comment by mathemakitten** [comment] 2020-01-09 17:44
I have also tried the following workflow which results in the same behaviour:

**main.py:** 
sweep_id = wandb.sweep(sweep_config)
wandb.agent(sweep_id, function=train_sweep(hparams, model, train_dataset_fn, eval_dataset_fn))

where train_sweep() looks like: 
```
wandb.init(project=MYPROJECT)
    for k in wandb.config.keys():
        hparams.__setattr__(k, wandb.config.__getattr__(k))
    model = Model(hparams)
    model.train(...)
```

**Comment by raubitsj** [comment] 2020-01-09 17:46
I think the issue is with:

```python
wandb.agent(sweep_id, function=train_sweep(hparams, model, train_dataset_fn, eval_dataset_fn))
```

function argument to wandb.agent() expects a function so unless train_sweep is returning a function you might want to do:

```python
wandb.agent(sweep_id, function=lambda: train_sweep(hparams, model, train_dataset_fn, eval_dataset_fn))
```

**Comment by mathemakitten** [comment] 2020-01-09 19:09
Thanks! I added the lambda and it's no longer returning a single run, but the sweep still doesn't seem to work. Here's what I get: 

```
2020-01-09 18:41:08,490 - wandb.wandb_agent - INFO - Running runs: []
INFO:wandb.wandb_agent:Running runs: []
2020-01-09 18:41:08,694 - wandb.wandb_agent - INFO - Agent received command: run
INFO:wandb.wandb_agent:Agent received command: run
2020-01-09 18:41:08,694 - wandb.wandb_agent - INFO - Agent starting run with config: 
MYCONFIGHERE
```
...

```
wandb: Agent Started Run: 9sa5tqqi
wandb: Tracking run with wandb version 0.8.19
wandb: Run data is saved locally in ...
wandb: Syncing run effortless-sweep-1
```

It *looks* like it's running correctly, but it just outputs this repeatedly: 
```2020-01-09 18:41:13,712 - wandb.wandb_agent - INFO - Running runs: ['9sa5tqqi']
INFO:wandb.wandb_agent:Running runs: ['9sa5tqqi']```

I eventually just had to kill it. Nothing was happening and no files were written to the wandb directory. Any thoughts?

**Comment by mathemakitten** [comment] 2020-01-09 20:04
Actually, do you have any examples of using W+B with workflows where sweeps get started up and launch a run on a new TPU? I think I'm having issues between the W+B sweep agent context and the way I'm connecting to the TPU (i.e. with TF functions like `tf.config.experimental_connect_to_cluster`). For some reason it works OK in single-run mode though.

**Comment by dkloving** [comment] 2020-04-25 15:51
> It _looks_ like it's running correctly, but it just outputs this repeatedly:
> 
> ```
> INFO:wandb.wandb_agent:Running runs: ['9sa5tqqi']
> ```
> 
> I eventually just had to kill it. Nothing was happening and no files were written to the wandb directory. Any thoughts?

I am having the same issue. The script works fine when it's allowed to create its own sweep_id via 

```
sweep_id = wandb.sweep(sweep_config, project='my-sweep')
```

but when it is given a sweep_id that's already been created it has the above described behavior. This prevents me from running more than 1 agent at a time.

**Comment by mathemakitten** [comment] 2020-04-25 17:00
@dkloving Are you using multiprocessing? It seems that wandb launches sweeps with multiprocessing which was conflicting with my TPU connector, which also uses multiprocessing.

**Comment by dkloving** [comment] 2020-04-25 19:47
Actually I just discovered that I get the problem when running on a Tesla V100 (p3 instance on EC2) but when running on my local (CPU) machine, both cases with a docker image.

**Comment by dkloving** [comment] 2020-04-25 20:21
Okay I figured out the problem- I was running out of memory! I had used the default 2GB config but needed substantially more. To figure this out I had to disable the wandb agent code and just run it as a normal single job.

I suggest improving the error handling for agents.

**Comment by ariG23498** [comment] 2020-12-03 04:50
Thanks for the ticket @dkloving 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Closed by ariG23498** 2020-12-03 04:50 UTC
Labels: bug, c:sweeps
