### ISSUE TITLE
Bayes sweep evaluates same set of parameters multiple times

### ISSUE THREAD

**Issue by michalmisiewicz** [wandb/client#1660] opened 2021-01-03 19:50 UTC
Given following configuration:
```python
sweep_config = {
    'name': 'my-awesome-sweep',
    'method': 'bayes',
    'metric': {
      'name': 'val_root_mean_squared_error',
      'goal': 'minimize'
    },
    'parameters': {
        'batch_size': {
            'values': [256, 512, 1024, 2048, 4096, 8192]
        },
        'learning_rate': {
            'values': [1e-2, 1e-3, 1e-4, 5e-4, 5e-5, 1e-5]
        },
        'activation': {
            'values': ['relu', 'elu', 'selu']
        }
    }
}
```

Bayes sweep evaluates same set of parameters multiple times:

![image](https://user-images.githubusercontent.com/16355374/103487347-f90ac380-4e04-11eb-81ca-f71f574187fa.png)

Is there any solution to evaluate set of parameters only once ?

**Comment by vanpelt** [comment] 2021-01-03 22:24
Hey @michalmisiewicz can you share a link to the sweep?

**Comment by michalmisiewicz** [comment] 2021-01-03 22:41
Hey @vanpelt, sure. [sweep url](https://wandb.ai/mm_magisterka/multimodal/sweeps/yjrws03e?workspace=user-mm_magisterka)

**Comment by sergeyk** [comment] 2021-02-22 02:31
Facing this issue too @vanpelt.

See top two rows here:
<img width="1920" alt="CleanShot 2021-02-21 at 18 26 47@2x" src="https://user-images.githubusercontent.com/4881/108649791-e3b02e00-7472-11eb-8e8b-8450a625dd59.png">

https://wandb.ai/sergeyk/fsdl-text-recognizer-2021-training/sweeps/twpvro2d/table?workspace=user-sergeyk

```
command:
  - ${env}
  - /home/sergeyk/miniconda3/envs/fsdl-text-recognizer-2021/bin/python
  - ${program}
  - "--wandb"
  - "--reduce_lr_on_plateau"
  - ${args}
program: training/run_experiment.py
method: bayes
metric:
  goal: minimize
  name: val_cer
early_terminate:
  type: hyperband
  min_iter: 20
parameters:
  early_conv_dim:
    values: [32, 64]
  late_conv_dim:
    values: [64, 128]
  window_width:
    values: [18, 24, 30]
  window_stride:
    values: [4, 8]
  fc_dim:
    values: [512, 1024, 2048]
  max_epochs:
    value: 1000
  num_workers:
    value: 20
  gpus:
    value: -1
  data_class:
    value: IAMLines
  model_class:
    values: [LineCNN, LineCNNLSTM]
  loss:
    value: ctc
  precision:
    value: 16
```

**Comment by vanpelt** [comment] 2021-02-22 17:32
Hey @sergeyk, just to be really clear on what you're seeing.  In the example above we searched the same set of parameters twice in your sweep and you would expect us to treat this search like a grid and never attempt the same combination of parameters more than once.  In addition, the sweep should finish once all combinations have been attempted.

If this sounds right, we'll reproduce on our end and figure out what the root cause is.

**Comment by sergeyk** [comment] 2021-02-22 19:21
That's right. Seeing this behavior in `random` mode also:
https://wandb.ai/sergeyk/fsdl-text-recognizer-2021-training/sweeps/iyckisfz/table?workspace=user-sergeyk

(I manually killed one of the runs below -- they both launched at the same time.)
<img width="1554" alt="CleanShot 2021-02-22 at 11 20 24@2x" src="https://user-images.githubusercontent.com/4881/108758563-1b18ec00-7500-11eb-89c6-419f0e3831a6.png">

**Comment by lukas** [comment] 2021-02-26 01:52
In random mode we sample with replacement and we should sample without replacement by default, I can get out a fix for this.

I believe what's happening in both of the bayes cases is that there are a small number of possible values and the gaussian process has some a small uncertaintly still on the hyperparameters where there is an observed value so it thinks that the most promising set of hyperparameters to try is one that it's used already. I can also special case this out so that it doesn't happen.

**Comment by sergeyk** [comment] 2021-02-26 02:51
Makes sense, thanks for your attention!

Cheers,
Sergey

**Comment by toliz** [comment] 2021-03-27 12:48
I am experiencing the same problem.

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/14910527/112721115-dae7c780-8f0a-11eb-81d3-ae589901dc71.png">

Note that some parameters (e.g. number of layers here) seems to get fixed pretty early. From the 33 experiments conducted, the sweep used 1 layer for 31 of them, and 2 or 3 layers only once.

Of course it's not possible to draw safe conclusions like that. Also I don't think it's really useful running the same config multiple times.

**Closed** 2022-01-06 02:54 UTC
Labels: bug

**Comment by hemanths03** [comment] 2022-02-20 12:45
Yes the issue is still there, we are facing the same issue

**Comment by franzigeiger** [comment] 2023-01-23 09:09
We are facing the same issue! Especially the bayes configuration gets stuck in one configuration set for us.

**Comment by Mionies** [comment] 2023-03-26 23:53
The issue is still here!

**Comment by MalekWahidi** [comment] 2024-01-05 19:37
Issue still here with wandb version  0.16.1!
