### ISSUE TITLE
wandb.watch(model) fails when using torch.nn.DataParallel(model)

### ISSUE THREAD

**Issue by timothybrooks** [wandb/client#847] opened 2020-02-07 07:04 UTC
* Weights and Biases version: 0.8.25
* Python version: 3.7.6
* Operating System: Linux

### Description

I am trying to call `wandb.watch(model)` to monitor the model, and also use `torch.nn.DataParallel(model)` for multi-GPU training. However, the two seem to be incompatible.

### What I Did

I have tried the following:
```
wandb.watch(model)
model = nn.DataParallel(model)
```
```
model = nn.DataParallel(model)
wandb.watch(model)
```
```
model = nn.DataParallel(model)
wandb.watch(model.module)
```

And all of them raise the same error, shown in the trace below.

```
Traceback (most recent call last):
  File "train.py", line 71, in <module>
    main()
  File "train.py", line 67, in main
    trainer.train(args.num_epochs)
  File "/home/timbrooks/code/adv_rec/training/trainer.py", line 78, in train
    self._step_decoder(image)
  File "/home/timbrooks/code/adv_rec/training/trainer.py", line 99, in _step_decoder
    loss.backward()
  File "/home/timbrooks/anaconda3/envs/adv_rec/lib/python3.7/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/timbrooks/anaconda3/envs/adv_rec/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/timbrooks/anaconda3/envs/adv_rec/lib/python3.7/site-packages/wandb/wandb_torch.py", line 359, in backward_hook
    wandb.run.summary["graph_%i" % graph_idx] = graph
  File "/home/timbrooks/anaconda3/envs/adv_rec/lib/python3.7/site-packages/wandb/summary.py", line 134, in __setitem__
    self._root._root_set(path, [(k, v)])
  File "/home/timbrooks/anaconda3/envs/adv_rec/lib/python3.7/site-packages/wandb/summary.py", line 254, in _root_set
    json_dict[new_key] = self._encode(new_value, path + (new_key,))
  File "/home/timbrooks/anaconda3/envs/adv_rec/lib/python3.7/site-packages/wandb/summary.py", line 323, in _encode
    friendly_value, converted = util.json_friendly(data_types.val_to_json(self._run, path, value))
  File "/home/timbrooks/anaconda3/envs/adv_rec/lib/python3.7/site-packages/wandb/data_types.py", line 1365, in val_to_json
    val.bind_to_run(run, key, step)
  File "/home/timbrooks/anaconda3/envs/adv_rec/lib/python3.7/site-packages/wandb/data_types.py", line 973, in bind_to_run
    super(Graph, self).bind_to_run(*args, **kwargs)
  File "/home/timbrooks/anaconda3/envs/adv_rec/lib/python3.7/site-packages/wandb/data_types.py", line 162, in bind_to_run
    raise RuntimeError('Value is already bound to a Run: {}'.format(self))
RuntimeError: Value is already bound to a Run
wandb: Waiting for W&B process to finish, PID 50739
: <wandb.wandb_torch.TorchGraph object at 0x7f3501e99950>
wandb: Program failed with code 1. Press ctrl-c to abort syncing.
wandb: Process crashed early, not syncing files
```

**Comment by raubitsj** [comment] 2020-02-07 23:36
Sorry this is caused by a regression with how we were recording the model graph.

Temporary workaround:
 `pip install wandb==0.8.22`

Will have a development fix soon, and we will have a release early next week at the latest.

**Comment by raubitsj** [comment] 2020-02-08 00:03
An experimental pip is available with this command:
pip install --upgrade git+git://github.com/wandb/client.git@fix/pytorch-watch-parallel#egg=wandb

**Comment by timothybrooks** [comment] 2020-02-08 01:56
Thank you!

**Comment by timothybrooks** [comment] 2020-02-08 08:52
Just tried out the experimental pip version. It indeed allows for watching the model, so thanks for the fix. 

However, in the model tab, the table listing Name/Type/# Parameters/Output Shape shows multiple entries for each submodule (one for each GPU). So if I train on 8 GPUs, I will see 8 copies of each submodule, which makes it quite confusing and cluttered to read. This even happens when I call watch on the underlying single-GPU module via `wandb.watch(model.module)`. I believe the correct behavior would be to only display a single copy of the model submodules, even if there are multiple copies of that model across the GPUs.

I am happy to create a new issue for this if you believe it is separate from the regression.

Thanks for the help!

**Comment by harritaylor** [comment] 2020-02-10 17:38
> An experimental pip is available with this command:
> pip install --upgrade git+git://github.com/wandb/client.git@fix/pytorch-watch-parallel#egg=wandb

Hit the same problem half an hour ago, thanks for the fix!

**Comment by raubitsj** [comment] 2020-02-10 19:52
Fixed in 0.8.26.

**Closed by raubitsj** 2020-02-10 19:52 UTC

**Comment by raubitsj** [comment] 2020-02-10 19:56
@timothybrooks, I noticed the duplicate layer logging (which was consistent with the earlier releases) but I wanted to get the failure fixed asap.  Feel free to file another issue for the duplicate layer logging so that you can be informed when we fix it.

**Comment by timothybrooks** [comment] 2020-02-10 20:33
Thanks for the fix! Just made a new issue for the duplicate logs:
https://github.com/wandb/client/issues/856
