### ISSUE TITLE
wandb local incomplete sync

### ISSUE THREAD

**Issue by noklam** [wandb/client#1066] opened 2020-05-27 05:36 UTC
wandb, version 0.8.36
Python 3.7.4
Window 10 

### Description
**Incomplete sync**
I am running the wandb Docker in local with `wandb local`. When I use `wandb sync`, it only sync parts of the experiment(config), but system metric, and charts are not sync (empty). I can see those metrics logged in local JSON file.

When I try to export the data to see if the metrics are sync properly, I get the error below

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /graphql (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])")))
wandb: Network error (SSLError), entering retry loop. See D:\Docker_Source\wandb\debug.log for full traceback.
```

### What I Did

```
wandb local
wandb sync
export data (from UI)
```

![image](https://user-images.githubusercontent.com/18221871/82981606-06fe9780-a01f-11ea-961d-64f0a1fa5d2f.png)

![image](https://user-images.githubusercontent.com/18221871/82981599-0108b680-a01f-11ea-9d59-f293febcded3.png)

**Comment by cvphelps** [comment] 2020-05-27 22:32
It looks like your local system is configured to speak to the local backend over SSL which is causing it to fail.  Can you try running `WANDB_BASE_URL=http://localhost:8080 wandb sync` and see if you're getting the same error.  When you run `wandb local` we write a settings file to your home directory with the base url and it may be set to https instead of http.  Can you show me the contents of `~/.config/wandb/settings`?

**Comment by noklam** [comment] 2020-05-28 00:05
You are right. I fixed the https issue and wandb sync run successfully but the issue of incomplete sync is still here,  it fails to sync the run history..

**Comment by vanpelt** [comment] 2020-05-28 00:17
Can you email a tar ball or zip of the local run directory to vanpelt@wandb.com so I can try to reproduce?

**Comment by noklam** [comment] 2020-05-28 01:33
@vanpelt  please check email

**Comment by vanpelt** [comment] 2020-05-28 15:55
Hey @noklam I was ably to sync the run to wandb and all metrics synced:

![image](https://user-images.githubusercontent.com/17/83164172-c2c3d380-a0c0-11ea-92c5-89dc12f05941.png)

Can you try running `wandb sync run-20200523_054348-23h9haz8` on the specific directory?  If your still seeing missing metrics can you give me examples of the specific metrics that are missing?

**Comment by noklam** [comment] 2020-05-28 16:19
@vanpelt  I try sync it on my local docker and app.wandb.ai, but I get empty metrics.
![image](https://user-images.githubusercontent.com/18221871/83166635-ccd9e680-a141-11ea-85b4-13823d34bb9b.png)

**Comment by vanpelt** [comment] 2020-05-28 16:39
I was able to sync it successfully on both cloud and onprem with the following command:

`wandb sync -p sync_test run-20200523_054348-23h9haz8`.

Can you run `wandb --version` to see what client library you're using.  I'm on 0.8.36

**Comment by noklam** [comment] 2020-05-28 16:55
`wandb, version 0.8.36`
Window 10
I run it on both cloud and local docker, result are the same.

**Comment by noklam** [comment] 2020-05-28 17:13
@vanpelt  Hi, I did some more digging. I use WSL and run `wandb sync` and now I can see the metrics, I guess something wrong with Window, I am not sure what is wrong as no error message was thrown.

**Comment by vanpelt** [comment] 2020-05-28 23:58
Ahh, good to know.  This should be fixed in our [new client library](https://github.com/wandb/client-ng) which has much better support for Windows.

**Closed by vanpelt** 2020-05-28 23:58 UTC

**Comment by noklam** [comment] 2020-05-29 01:59
@vanpelt  Is this new client library working? or it will be released in coming releases?

**Comment by noklam** [comment] 2020-05-29 02:01
FYI, I checked when I run  `wandb sync`, the response from the stream API are all success `Response [200]`, I will use WSL as a temp solution for now, thx.

**Comment by vanpelt** [comment] 2020-05-29 17:57
@noklam we're currently catching up to feature equivalence to our core library, but it's functional today.  The next release will include new and improved sync support and should be released first thing next week.

**Comment by noklam** [comment] 2020-05-30 08:45
Good to know, looking forward to the new release.  Appreciate your help!
