### ISSUE TITLE
Missing code file when using jupyter-lab

### ISSUE THREAD

**Issue by andrashee** [wandb/client#485] opened 2019-08-15 12:58 UTC
* Weights and Biases version: 0.8.8
* Python version: 3.7
* Operating System: docker, ubuntu, jupyter-lab

### Description

When using the attached notebook I get the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/app/notebooks/wandb/run-20190815_122626-y9w00bpa/code/notebooks/wandb.ipynb'
```
When looking into the `/app/notebooks/wandb/run-20190815_122626-y9w00bpa/code/` directory, one can see that the file is indeed missing. It seems that wandb couldn't copy the current notebook file into the wandb directory.
Is there an error how I'm using wandb or is this a bug?

### What I Did
See notebook:
[wandb.ipynb](https://github.com/wandb/client/files/3505559/wandb.ipynb.txt)

**Comment by vanpelt** [comment] 2019-08-15 16:25
This definitely looks like a bug.  A quick fix would be to run `os.environ['WANDB_NOTEBOOK_NAME']="wandb.ipynb"` before calling `wandb.init`, I'll look into the root cause.

**Comment by vanpelt** [comment] 2019-08-18 23:00
I have a fix for this coming out in 0.8.9.  You can install the cli from master to use the fix now, you don't need to specify the notebook name:  `pip install --upgrade git+git://github.com/wandb/client.git@master#egg=wandb`

**Comment by andrashee** [comment] 2019-08-19 09:17
Many thanks for the quick fix. Works now like a charm 💯

**Closed** 2019-08-19 09:18 UTC
Labels: bug

**Comment by vanpelt** [comment] 2019-08-20 00:41
0.8.9 was released today which has the fix!
