### ISSUE TITLE
Ugly errors when backend is failing

### ISSUE THREAD

**Issue by vanpelt** [wandb/client#146] opened 2018-03-04 21:57 UTC
My local redis server died and when I ran something locally, here was the output to the terminal:

```bash
Traceback (most recent call last):
  File "/Users/vanpelt/Development/WandB/core/frontends/client/wandb/retry.py", line 79, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/vanpelt/.pyenv/versions/tensorflow-2.7/lib/python2.7/site-packages/gql/client.py", line 50, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/vanpelt/.pyenv/versions/tensorflow-2.7/lib/python2.7/site-packages/gql/client.py", line 73, in _get_result
    raise RetryError(retries_count, last_exception)
RetryError: Failed 1 retries: 400 Client Error: Bad Request for url: http://gql.test/graphql
Repeat: 0, Epoch: 1, accuracy: 0.35683675934
Repeat: 0, Epoch: 2, accuracy: 0.610605562693
Repeat: 0, Epoch: 3, accuracy: 0.144500147504
Pretty blue
Traceback (most recent call last):
  File "/Users/vanpelt/Development/WandB/core/frontends/client/wandb/retry.py", line 79, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/vanpelt/.pyenv/versions/tensorflow-2.7/lib/python2.7/site-packages/gql/client.py", line 50, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/vanpelt/.pyenv/versions/tensorflow-2.7/lib/python2.7/site-packages/gql/client.py", line 73, in _get_result
    raise RetryError(retries_count, last_exception)
RetryError: Failed 1 retries: 400 Client Error: Bad Request for url: http://gql.test/graphql
Repeat: 0, Epoch: 1, accuracy: 0.35683675934
Repeat: 0, Epoch: 2, accuracy: 0.610605562693
Repeat: 0, Epoch: 3, accuracy: 0.144500147504
Pretty blue
Traceback (most recent call last):
  File "/Users/vanpelt/Development/WandB/core/frontends/client/wandb/retry.py", line 79, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/vanpelt/.pyenv/versions/tensorflow-2.7/lib/python2.7/site-packages/gql/client.py", line 50, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/vanpelt/.pyenv/versions/tensorflow-2.7/lib/python2.7/site-packages/gql/client.py", line 73, in _get_result
    raise RetryError(retries_count, last_exception)
RetryError: Failed 1 retries: 400 Client Error: Bad Request for url: http://gql.test/graphql
Repeat: 0, Epoch: 4, accuracy: 0.10778700667
Repeat: 0, Epoch: 5, accuracy: 0.719535913481
Repeat: 0, Epoch: 6, accuracy: 0.0455859299644
Pretty blue
wandb network error (RetryError), entering retry loop. See wandb/debug.log for full traceback.
Traceback (most recent call last):
  File "/Users/vanpelt/Development/WandB/core/frontends/client/wandb/retry.py", line 79, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/vanpelt/.pyenv/versions/tensorflow-2.7/lib/python2.7/site-packages/gql/client.py", line 50, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/vanpelt/.pyenv/versions/tensorflow-2.7/lib/python2.7/site-packages/gql/client.py", line 73, in _get_result
    raise RetryError(retries_count, last_exception)
RetryError: Failed 1 retries: 400 Client Error: Bad Request for url: http://gql.test/graphql
Repeat: 0, Epoch: 7, accuracy: 0.120346332271
Someother stuff 7
Repeat: 0, Epoch: 8, accuracy: 0.82121719103
Found new best epoch, setting summary
Repeat: 0, Epoch: 9, accuracy: 0.0765244702333
Pretty blue

wandb: Program ended.
```

**Comment by adrianbg** [comment] 2018-04-25 16:45
Tried to reproduce by running all services except Redis locally. I got periodic "network error" messages, but no tracebacks.

**Comment by adrianbg** [comment] 2018-04-26 00:54
Nevermind - seeing something very similar when I run a script with no services running. The problem is that `gql` uses the root logger instead of making its own. It's fixed in git but there's no way of depending on a git version of a package in `setup.py`. I don't see an easy/good way of fixing this for the time being. I'd rather not mess much with the root logger because user scripts are likely to be using it.

```
WARNING:root:Request failed with exception HTTPConnectionPool(host='gql.test', port=80): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10597fe50>: Failed to establish a new connection: [Errno 61] Connection refused',)). Retrying for the 1 time...
Traceback (most recent call last):
  File "/Users/adrian/.pyenv/versions/2.7.12/envs/wandb-2.7/lib/python2.7/site-packages/gql/client.py", line 64, in _get_result
    result = self.transport.execute(document, *args, **kwargs)
  File "/Users/adrian/.pyenv/versions/2.7.12/envs/wandb-2.7/lib/python2.7/site-packages/gql/transport/requests.py", line 37, in execute
    request = requests.post(self.url, **post_args)
  File "/Users/adrian/.pyenv/versions/2.7.12/envs/wandb-2.7/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/adrian/.pyenv/versions/2.7.12/envs/wandb-2.7/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/adrian/.pyenv/versions/2.7.12/envs/wandb-2.7/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/adrian/.pyenv/versions/2.7.12/envs/wandb-2.7/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Users/adrian/.pyenv/versions/2.7.12/envs/wandb-2.7/lib/python2.7/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='gql.test', port=80): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10597fe50>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

**Comment by vanpelt** [comment] 2018-04-26 01:08
We could make our own transport that caught the ConnectionError and wrote to our own logger: https://github.com/graphql-python/gql/blob/master/gql/transport/requests.py

**Closed** 2018-04-27 00:52 UTC

**Comment by adrianbg** [comment] 2018-04-27 00:55
Turned out not to be necessary. The GQL logging was happening in the W&B process, not the user process, so it was okay to direct all logging to debug.log.
