### ISSUE TITLE
Web app can't show plotly figure or html

### ISSUE THREAD

**Issue by zkx741481546** [wandb/client#999] opened 2020-04-25 16:02 UTC
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.33
* Python version: 3.7
* Operating System: win10

### Description

When I log a plotly.Figure object, the web just keep loading media and finally shows `This run didn't log tables for key "episode", step 0, index 0. Docs →`
And if I log a html generated by plotly, I got `{"error":"file 7cr24d2r/media/html/test_27_15c82899.html not found while downloading file"}.`
But the html file and the plotly json object is indeed in the wandb folder.

### What I Did

Here is my code of log Figure
`conf = { "data": [profit_scatter, base_scatter, price_scatter, trade_bar,
                     amount_scatter],
            "layout": go.Layout(
                title=self.stock_code + " 回测结果" + "     初始资金：" + str(
                    self.principal) + "     初始股票总量(股)：" + str(
                    self.origin_stock_amount),
                xaxis=dict(title='日期', type="category", showgrid=False, zeroline=False),
                yaxis=dict(title='收益率', showgrid=False, zeroline=False, titlefont={'color': 'red'},
                           tickfont={'color': 'red'}),
                yaxis2=dict(title='股价', overlaying='y', side='right',
                            titlefont={'color': 'orange'}, tickfont={'color': 'orange'},
                            showgrid=False,
                            zeroline=False),
                yaxis3=dict(title='交易量', overlaying='y', side='right',
                            titlefont={'color': '#000099'}, tickfont={'color': '#000099'},
                            showgrid=False, position=0.97, zeroline=False, anchor='free'),
                yaxis4=dict(title='持股量', overlaying='y', side='left',
                            titlefont={'color': '#00ccff'}, tickfont={'color': '#00ccff'},
                            showgrid=False, position=0.03, zeroline=False, anchor='free'),
                paper_bgcolor='#000000',
                plot_bgcolor='#000000'
            )
        }

        if self.mode == 'train':

            fig = go.Figure(conf)

            wandb.log({"episode":  wandb.data_types.Plotly(fig)})`
sorry for the code format, I just can't make the conf part display right.

**Comment by zkx741481546** [comment] 2020-04-25 16:06
I also tried `wandb.log({"episode": fig})`, same problem too

**Comment by zkx741481546** [comment] 2020-04-25 17:13
it seems that after my program exit, I can see the media in web app. And if I manually stop the program in pycharm, it will show that html not found error. Is there any way to show html while the program running?

**Comment by zkx741481546** [comment] 2020-04-26 02:31
this is the test code I mentioned on the forum 
`import wandb
wandb.init(project='temp')
for i in range(0,100):
    wandb.log({'test':wandb.Html(open('E:\运行结果\TRPO\TRPO\\test\episode_'+str(i)+'.html'))},sync=False)
    if i == 20:
        wandb.join()
        while True:
            pass
`

**Comment by vanpelt** [comment] 2020-04-27 00:10
This is likely caused by the UTF-8 characters in your figures.  We'll take a look this week and hopefully get a fix together.

**Comment by ariG23498** [comment] 2020-12-03 06:46
Hey @zkx741481546 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Closed by ariG23498** 2020-12-03 06:46 UTC

**Comment by shalini-maiti** [comment] 2022-10-04 10:22
Hello, I've been facing this issue as well. Some of my runs don't log any media - video or figures, especially if I run multiple jobs in parallel.
