### ISSUE TITLE
wandb is leaking file pointers?

### ISSUE THREAD

**Issue by alsuhr-c** [wandb/client#1447] opened 2020-10-31 17:23 UTC
In my code, I am creating and closing wandb loggers to different projects (I have multiple training pipelines running at the same time). I noticed that wandb seems to be leaking open files. This is causing problems with my code because at a certain point there are too many open files so the job is killed.

Here is a script which replicates this problem:

```
import psutil
import wandb

def print_file_info():
    proc = psutil.Process()
    print('Num open files: %s' % len(proc.open_files()))
    for filename in proc.open_files():
        print('\t%s' % filename.path)

print('Before any WANDB stuff')
print_file_info()
run = wandb.init(project='test', name='test', reinit=True, resume='allow')
run_id = run.id
run.finish()

print('After creating run and getting run ID')
print_file_info()
run = wandb.init(id=run_id, project='test', name='test', reinit=True, resume='allow')
run.finish()

print('After accessing run again')
print_file_info()

test_file = open('test_file.txt', 'w')
print('After creating a normal file pointer')
print_file_info()

test_file.close()
print('After closing that file')
print_file_info()
```

If I run with `WANDB_SILENT=true python wandb_file_leak_test.py`, the output will be something like: 

```
Before any WANDB stuff
Num open files: 0


After creating run and getting run ID
Num open files: 1
	/home/alsuhr/Documents/testing/wandb/run-20201031_132102-j0ebkg08/logs/debug.log


After accessing run again
Num open files: 2
	/home/alsuhr/Documents/testing/wandb/run-20201031_132102-j0ebkg08/logs/debug.log
	/home/alsuhr/Documents/testing/wandb/run-20201031_132106-j0ebkg08/logs/debug.log
After creating a normal file pointer
Num open files: 3
	/home/alsuhr/Documents/testing/wandb/run-20201031_132102-j0ebkg08/logs/debug.log
	/home/alsuhr/Documents/testing/wandb/run-20201031_132106-j0ebkg08/logs/debug.log
	/home/alsuhr/Documents/testing/test_file.txt
After closing that file
Num open files: 2
	/home/alsuhr/Documents/testing/wandb/run-20201031_132102-j0ebkg08/logs/debug.log
	/home/alsuhr/Documents/testing/wandb/run-20201031_132106-j0ebkg08/logs/debug.log
```

Notice how the test file is opened and then the file pointer to it is gone in the last check. What is going on? How can I make sure that these file pointers are actually closed by wandb?

Thanks!

Forgot to mention:
* wandb version 0.10.8
* python version 3.7.6
* `uname -a`: Linux bigbox 4.15.0-112-generic #113~16.04.1-Ubuntu SMP Fri Jul 10 04:37:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

More details:
* I can replicate this even if I remove `reinit=True` and `resume='allow'`.
* The documentation seems to suggest this file is only being written to if `WANDB_SILENT=true` (https://docs.wandb.com/library/environment-variables#optional-environment-variables). However, I can replicate this even I remove that environment variable (just set it above so it's easier to read the output).

**Comment by alsuhr-c** [comment] 2020-10-31 17:54
I think the problem is that in the `finish` function for a run (here: https://github.com/wandb/client/blob/7a374ef36a6e22e0de198b4812afe9fc3b286110/wandb/sdk/wandb_run.py#L1012), while the handlers are removed from the logger (one of the teardown hooks, set here: https://github.com/wandb/client/blob/7a374ef36a6e22e0de198b4812afe9fc3b286110/wandb/sdk/wandb_init.py#L191), the handler is not actually closed. 

I actually see a comment there that it should be closed. Adding a teardown hook like this, replacing line 190:

```
self._teardown_hooks.append(lambda: handler.close())
```

Fixes the problem. Should I create a PR?

**Comment by tyomhak** [comment] 2020-11-02 08:24
Hey @alsuhr-c , thanks for reporting and looking into it! 
@vanpelt  @raubitsj can you please check this out?

**Comment by vanpelt** [comment] 2020-11-02 17:18
@alsuhr-c a PR would be great.  We can just add the handler.close before removing the handler in the existing hook.  Be sure to run `make test` after changing the files so that we properly generate `wandb_init.py` in the `sdk_py27` directory.

**Comment by alsuhr-c** [comment] 2020-11-04 17:20
I can create a PR for this but I found another issue where something similar is happening. I am getting an error that too many files are open for this call (this has happened consistently across several runs):

https://github.com/wandb/client/blob/e9b843e0e2da88b5edf9e4d54a347eceff0489ff/wandb/sdk/backend/backend.py#L81

It is specifically crashing on this line in the multiprocessing library, which seems to suggest that these pipes are not being closed properly given that it's always crashing on this line (although, I could be wrong):

https://github.com/python/cpython/blob/master/Lib/multiprocessing/util.py#L450

**Comment by alsuhr-c** [comment] 2020-11-04 21:27
I'm not sure if this is related, but I am getting an error where when I kill my own process, it gives me an error in the traceback:

```
/home/alsuhr/anaconda3/envs/cereal_bar/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 30 leaked semaphores to clean up at shutdown
```

**Comment by timwitty** [comment] 2021-01-31 21:36
> I think the problem is that in the `finish` function for a run (here:
> 
> https://github.com/wandb/client/blob/7a374ef36a6e22e0de198b4812afe9fc3b286110/wandb/sdk/wandb_run.py#L1012
> 
> ), while the handlers are removed from the logger (one of the teardown hooks, set here:
> https://github.com/wandb/client/blob/7a374ef36a6e22e0de198b4812afe9fc3b286110/wandb/sdk/wandb_init.py#L191
> 
> ), the handler is not actually closed.
> I actually see a comment there that it should be closed. Adding a teardown hook like this, replacing line 190:
> 
> ```
> self._teardown_hooks.append(lambda: handler.close())
> ```
> 
> Fixes the problem. Should I create a PR?

@alsuhr-c I wonder if it may be worth a PR for this specific issue and another separate PR/issue for the other problem you may have found. It would at least solve this definite issue.

I just tested your change one of my runs failed with a `Too Many Open Files` exception. I validated that a file was being leaked with your initial code in this issue. And then tested your change and it was no longer leaking.

I've not run into an error at the other location mention at this time.

I too get the leaked semaphore warning when exiting my own process.

**Comment by alsuhr-c** [comment] 2021-01-31 21:45
Hi, sorry, I actually haven't worked on this as I figured out a workaround for the second issue (basically I made it so my code only opens wandb at max a few times per process) and got caught up in my research. 

I had started creating a PR but couldn't set up the testing environment for wandb iirc (or something else was hard to get working on my machine) and other things came up so I forgot. I can try creating one again (it's on my todo list) but no promises when I can get it done due to deadlines / etc. Thanks!

**Comment by raubitsj** [comment] 2021-01-31 22:31
Thanks for the reproduction cases, we have raised the priority and will get this fixed soon.

**Comment by timwitty** [comment] 2021-02-01 02:33
> Hi, sorry, I actually haven't worked on this as I figured out a workaround for the second issue (basically I made it so my code only opens wandb at max a few times per process) and got caught up in my research.
> 
> I had started creating a PR but couldn't set up the testing environment for wandb iirc (or something else was hard to get working on my machine) and other things came up so I forgot. I can try creating one again (it's on my todo list) but no promises when I can get it done due to deadlines / etc. Thanks!

I just ran into another too many open files error similar to the second issue. Only got a little farther in my run after applying the first fix.

Looks like I'll have to either stop using wandb for similar tool or go similar route to try and fix. Not really wanting to do either.

**Comment by farizrahman4u** [comment] 2021-02-03 21:47
@timwitty Do you have a reproduction case for the second issue?

**Comment by timwitty** [comment] 2021-02-03 22:17
@farizrahman4u Yes, I should have included it. Its very basic. I can't include the exact script. But I've provided a reasonable facsimile here. I'll run it when I have time between my current runs to validate it does reproduce the issue.

The param grid feeding to make_classification is 1600. In the past I've seen issue around 1k-1.3k runs.

- Macbook Pro 32GB RAM, Mojave.
- wandb 0.10.14 (will try upgrading soon)
- I'm also running this with the self hosted local setup. I've not an issue with the server component, but obviously it could contribute to the too many open files.

```
import errno
import sys
import wandb
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, ParameterGrid
from sklearn.datasets import make_classification

def model_algorithm(clf_class, params, x_train, y_train, x_test, y_test, name, labels, features):
    clf = clf_class(**params)
    clf.fit(x_train, y_train)
    labels = clf.classes_
    y_probas = clf.predict_proba(x_test)
    y_pred = clf.predict(x_test)
    # I log some metrics like f1 score, accurracy to wandb
    #  < log 7 images to wandb and the wandb classification plots>


if __name__ == '__main__':
    project = "test"
    dataset_grid = dict(
        n_samples=[2500, 5000, 7500, 10000],
        n_features=[10, 15, 20],
        n_informative=[2, 4, 6, 8],
        n_redundant=[0, 2, 4, 6, 8],
        n_classes=[2],
        weights=[[0.5], [0.6], [0.7], [0.8]],
        random_state=[2021]
    )
    dataset_params_grid = list(ParameterGrid(dataset_grid))
    for dataset_params in dataset_params_grid:
        if dataset_params['n_features'] < (dataset_params['n_informative'] + dataset_params['n_redundant']):
            wandb.termlog(f"Skipped feature set that didn't add up: {dataset_params}")
            continue
        weight = dataset_params['weights'][0]
        x, y = make_classification(**dataset_params)
        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
        clf = DecisionTreeClassifier
        name = "DecisionTree"
        params = {'max_depth': 3}
        try:
            run = wandb.init(project=project, anonymous='allow', reinit=True, config=params)
        except OSError as err:
            if err.errno == errno.EMFILE:
                # too many files open
                sys.exit(85)
        except Exception as ex:
            if str(ex) == "problem":
                # This is a general exception from wandb. So far only seen too many open files error.
                sys.exit(85)

        run.name = f"{name}-{dataset_params['n_informative']}-{dataset_params['n_samples']}"
        wandb.log(dataset_params)
        wandb.log({'weight': weight})
        model_algorithm(clf, params, x_train, y_train, x_test, y_test, f"{name}")
        run.finish()
```

**Comment by timwitty** [comment] 2021-02-04 00:18
I was able to reproduce with example I gave after a little over 1100 runs generated, but got a different traceback of the too many open files exception. My try/except still did not actually catch this which doesn't make sense to me atm.

I also didn't even add anything for the below lines from the example to get the below. Perhaps if added they produce another version of this error.

```
    # I log some metrics like f1 score, accurracy to wandb
    #  < log 7 images to wandb and the wandb classification plots>
```

Essentially any long run I do similar to this fails with too many open files exception. Additionally, as noted earlier when exiting the script manually there is a warning about leaked semaphores. Not sure if that could be related.

```
Problem at: min.py 41 <module>
Traceback (most recent call last):
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 618, in init
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 393, in init
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/backend/backend.py", line 53, in ensure_launched
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/context.py", line 102, in Queue
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/queues.py", line 47, in __init__
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/context.py", line 67, in Lock
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
OSError: [Errno 24] Too many open files
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 618, in init
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 393, in init
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/backend/backend.py", line 53, in ensure_launched
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/context.py", line 102, in Queue
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/queues.py", line 47, in __init__
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/context.py", line 67, in Lock
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
OSError: [Errno 24] Too many open files

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "min.py", line 41, in <module>
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 655, in init
  File "<string>", line 3, in raise_from
Exception: problem

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "min.py", line 49, in <module>
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 80, in exit
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 80, in exit
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 80, in exit
  [Previous line repeated 996 more times]
RecursionError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/weakref.py", line 624, in _exitfunc
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/weakref.py", line 548, in __call__
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/tempfile.py", line 799, in _cleanup
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/shutil.py", line 482, in rmtree
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/shutil.py", line 480, in rmtree
OSError: [Errno 24] Too many open files: '/var/folders/mt/qb2m6nnn5251r4gwdqjm3n2m0000gp/T/tmp7emqpnz3wandb'
Traceback (most recent call last):
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/weakref.py", line 624, in _exitfunc
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/weakref.py", line 548, in __call__
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/tempfile.py", line 799, in _cleanup
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/shutil.py", line 482, in rmtree
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/shutil.py", line 480, in rmtree
OSError: [Errno 24] Too many open files: '/var/folders/mt/qb2m6nnn5251r4gwdqjm3n2m0000gp/T/tmpyxvvkqziwandb-media'
```

These are the other versions.

```
Problem at: train.py 304 main
Traceback (most recent call last):
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 618, in init
    run = wi.init()
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 393, in init
    use_redirect=use_redirect,
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/backend/backend.py", line 82, in ensure_launched
    self.wandb_process.start()
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 59, in _launch
    cmd, self._fds)
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/util.py", line 412, in spawnv_passfds
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 618, in init
    run = wi.init()
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 393, in init
    use_redirect=use_redirect,
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/backend/backend.py", line 82, in ensure_launched
    self.wandb_process.start()
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 59, in _launch
    cmd, self._fds)
  File "/Users/timwitty/.asdf/installs/python/3.6.10/lib/python3.6/multiprocessing/util.py", line 412, in spawnv_passfds
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 330, in <module>
    typer.run(main)
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/typer/main.py", line 859, in run
    app()
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "train.py", line 304, in main
    run = wandb.init(project=project, anonymous='allow', name=f"{name}", reinit=True, config=params)
  File "/Users/timwitty/code/venv/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 655, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem
```

**Comment by GillesJ** [comment] 2021-04-16 08:49
I am having the same issue and seeing the following errors in terminal:
- OSError: Too many open files
- shell is throwing leaked semaphore warnings `home/gilles/.pyenv/versions/3.8.8/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 822 leaked semaphore objects to clean up at shutdown`

**Comment by vanpelt** [comment] 2021-04-16 17:59
Hey @GillesJ we're looking into this.  In the mean time, you can avoid this by calling `wandb agent sweep_id` from the command line and configure the sweep to execute a program that calls the `train` function.

**Comment by GillesJ** [comment] 2021-05-04 11:18
I don't know for sure whether it was update 0.10.28 or updating `tqdm` to latest (which I was using and some indicate this could be a problem too), but the crashes with OSError for FileDescriptor limit have stopped. I do keep getting shell warnings for leaked semaphore objects if I interrupt the training process though.

**Comment by vanpelt** [comment] 2021-05-04 17:42
Thanks for the update.  We just released 0.10.29 that will give us more debugging information about the leaked semaphores (this means python thinks sub processes should still exist, but it can't find them).

**Comment by mtkinit** [comment] 2021-07-26 12:47
> I don't know for sure whether it was update 0.10.28 or updating `tqdm` to latest (which I was using and some indicate this could be a problem too), but the crashes with OSError for FileDescriptor limit have stopped. I do keep getting shell warnings for leaked semaphore objects if I interrupt the training process though.

In my case, I tried to stop using TQDM (it was only used in 3 loops). After that, the problem with file handles disappeared.

**Comment by sydholl** [comment] 2022-01-06 02:48
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Closed by sydholl** 2022-01-06 02:48 UTC
Labels: bug

**Comment by Exr0n** [comment] 2022-07-22 08:19
Comment to repoen: running into the same issues (both too many files and leaked semaphores) on `wandb=0.12.21`, Python 3.9.13, MacOS Big Sur 11.6. 

Code to reproduce:
```python
import wandb
for i in range(100):
    with wandb.init(entity='exr0nprojects', project='snap', group='useless'):
        print(f"run number {i}")
```
The "leaked semaphores" appears during the first run, but this may be happening because I've been testing in the same shell. The full error:
```
/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 54 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

I got the "too many open files" error after the 18th run. The error message is quite long, but appears to just repeat the following segment:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 556, in init
    backend.ensure_launched()
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/backend/backend.py", line 220, in ensure_launched
    self.wandb_process.start()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 58, in _launch
    self.pid = util.spawnv_passfds(spawn.get_executable(),
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/util.py", line 450, in spawnv_passfds
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files

The above exception was the direct cause of the following exception: [etc]
```

**Comment by erlebach** [comment] 2023-06-01 14:51
I am getting a similar problem: too many files open. Is anybody working on this?
