### ISSUE TITLE
Cannot use training_args.logging_steps of Hugging Face Trainer

### ISSUE THREAD

**Issue by minhtriet** [wandb/client#1053] opened 2020-05-21 12:35 UTC
* Weights and Biases version: version 0.8.35
* Python version: 3.7.6
* Operating System: Linux

### Description
I wanted to use Pytorch Trainer, this works
```python
from transformers import TrainingArguments
training_args = TrainingArguments("/kaggle/working")
...
# training_args.logging_steps=2
...
from transformers import Trainer

trainer = Trainer(
        model=model,
        args=training_args,...)
```
This does not, I received `You can only call wandb.watch once per model`
```python
from transformers import TrainingArguments
training_args = TrainingArguments("/kaggle/working")
...
training_args.logging_steps=2

from transformers import Trainer

trainer = Trainer(
        model=model,
        args=training_args,...)
```

**Comment by borisdayma** [comment] 2020-05-21 14:55
Can you try to restart your kernel?
Also maybe remove the wandb folder created. I think it's due to the importing of wandb which tries to look into this unrelated folder sometimes.

Let me know if that solves it and we can look into a permanent fix.

**Comment by vanpelt** [comment] 2020-05-21 14:58
You can also set `os.environ["WANDB_WATCH"] = "false"` before instantiating your trainer to disable the watching functionality.

**Comment by minhtriet** [comment] 2020-05-23 19:28
> Can you try to restart your kernel?
> Also maybe remove the wandb folder created. I think it's due to the importing of wandb which tries to look into this unrelated folder sometimes.
Hi, restarting kernel does not helps with the `training_args.logging_steps=2` parameters. However, it seems to  be compulsory to restarts kernel after every `trainer.train()`.

Removing the wandb folder gives the following error
```
ipython-input-95-3435b262f1ae> in <module>
----> 1 trainer.train()

/opt/conda/lib/python3.7/site-packages/transformers/trainer.py in train(self, model_path)
    323             self.tb_writer.add_hparams(self.args.to_sanitized_dict(), metric_dict={})
    324         if is_wandb_available():
--> 325             self._setup_wandb()
    326 
    327         # Train!

/opt/conda/lib/python3.7/site-packages/transformers/trainer.py in _setup_wandb(self)
    264         One can override this method to customize the setup if needed.
    265         """
--> 266         wandb.init(name=self.args.logging_dir, config=vars(self.args))
    267         # keep track of model topology and gradients
    268         wandb.watch(self.model)

/opt/conda/lib/python3.7/site-packages/wandb/__init__.py in init(job_type, dir, config, project, entity, reinit, tags, group, allow_val_change, resume, force, tensorboard, sync_tensorboard, monitor_gym, name, notes, id, magic, anonymous, config_exclude_keys, config_include_keys)
    914             if len(_global_run_stack) > 1:
    915                 termwarn("If you want to track multiple runs concurrently in wandb you should use multi-processing not threads")
--> 916             join()
    917         run = None
    918 

/opt/conda/lib/python3.7/site-packages/wandb/__init__.py in join(exit_code)
    564     shutdown_async_log_thread()
    565     if run:
--> 566         run.close_files()
    567     if len(_global_run_stack) > 0:
    568         _global_run_stack.pop()

/opt/conda/lib/python3.7/site-packages/wandb/wandb_run.py in close_files(self)
    744             self._events = None
    745         if self._history is not None:
--> 746             self._history.close()
    747             self._history = None
    748 

/opt/conda/lib/python3.7/site-packages/wandb/history.py in close(self)
    258 
    259     def close(self):
--> 260         self._write()
    261         self._lock.acquire()
    262         try:

/opt/conda/lib/python3.7/site-packages/wandb/history.py in _write(self)
    230         # for resuming.
    231         if self._file == None:
--> 232             self._file = open(self.fname, 'a')
    233         if self.row:
    234             self._lock.acquire(
```

> Let me know if that solves it and we can look into a permanent fix.

**Comment by borisdayma** [comment] 2020-05-23 22:08
Do you have a reproducible example?
It may be an edge case we've not seen yet.

**Comment by minhtriet** [comment] 2020-05-25 12:24
Since this is on Kaggle, I would share the notebook [here](https://www.kaggle.com/minhtriet/test-toxic). In the Settings menu on the right panel, please (1) Enable Internet for the kernel and (2) Use the lastest enviroment as seen in screenshot below
![screenshot](https://user-images.githubusercontent.com/2603847/82812430-48fad280-9e93-11ea-9337-909023f133f8.png)

**Comment by borisdayma** [comment] 2020-06-02 19:03
Can you confirm which dataset to use?

@vanpelt I actually get the same problem on huggingtweets which is why I make people restart the kernel after one training iteration.
Should we put this issue on hold for a little bit and try to close it with the upcoming CLI?

**Comment by Masum06** [comment] 2020-10-27 12:09
> remove the wandb folder created.

This solved for me. Thanks @borisdayma!

**Comment by vanpelt** [comment] 2020-10-27 18:01
The error in this thread seems to be connected to "removing the wandb director".  @borisdayma what error were you referring to here?  Is this still an issue?

**Comment by borisdayma** [comment] 2020-10-27 19:43
I've not seen it anymore with the latest wandb version.
I think it can be closed.

@minhtriet can you confirm this doesn't happen anymore for you as well?

**Comment by ariG23498** [comment] 2020-12-03 07:00
Hey @minhtriet 
Due to the inactivity of the thread and the solution being found we are closing this thread. Please feel free to reopen this is need be. :smile:

**Closed by ariG23498** 2020-12-03 07:00 UTC
