### ISSUE TITLE
Resume with tensorboard

### ISSUE THREAD

**Issue by ecatkins** [wandb/client#859] opened 2020-02-11 14:47 UTC
* Weights and Biases version: 0.8.25
* Python version: 3.5.3
* Operating System: Debian Stretch

### Description

I have been using Weights and Biases to import the Tensorboard results while I train a model using the standard Tensorflow Object detection library. This has worked effectively for me my placing the `init` function at the top of the [model_main.py](https://github.com/tensorflow/models/blob/master/research/object_detection/model_main.py) file i.e.:

```
wandb.init(sync_tensorboard=True)
```

However, if I pause and resume training I am unable to get it to "resume" with Weights & Biases, either by passing `resume=True` or `resume="run_id"`, and I'll see results like the ones  shown below. Am I doing something wrong? Or is the resume function not supported for Tensorboard currently?

![image](https://user-images.githubusercontent.com/8319226/74246984-59f05100-4cb3-11ea-851a-d72a977209db.png)

**Comment by cvphelps** [comment] 2020-02-15 18:26
Hi Edward, thanks for the question. @vanpelt do you think wandb resuming doesn't support TensorBoard at the moment?

**Comment by vanpelt** [comment] 2020-02-15 19:30
The charts being shown here are actually from 2 separate runs, so it looks like an error with actually resuming the run.  We'll need to reproduce on our end to see what's going on under the hood.  @ecatkins heads up that resume=True will only work if the initial run exits unsuccessfully and the resumed run is started from the same machine.

**Comment by shawnlewis** [comment] 2020-02-17 16:27
@ecatkins, you need to set `resume=True` and `id=<A_UNIQUE_ID_FOR_THIS_RUN>`. Use the same ID to reserve the run that you previously had that ID for.

**Comment by ariG23498** [comment] 2020-12-03 05:17
Hey @ecatkins 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Closed by ariG23498** 2020-12-03 05:17 UTC
