### ISSUE TITLE
Unexpected and malformed update config object with key `wandb_version` when resuming run, not originally included in the pushed config.

### ISSUE THREAD

**Issue by quebin31** [wandb/client#1481] opened 2020-11-11 03:13 UTC
**Python version:** `3.8`
**Wandb version:** `0.10.10`
**OS:** Linux

**Sample code failing:**
```python
if args.config:
    with open(args.config, 'r') as f:
        config = yaml.load(f)
else:
    config = None

resume = 'allow' if args.id else None
wandb.init(project='icl-vae', 
           entity='kdelcastillo',
           id=args.id,
           resume=resume,
           allow_val_change=True)
wandb.save('*.pt')
wandb.config.update(config)
config = wandb.config
```

By the stack trace output it seems that it's failing on `wandb.init`.

**Output/stacktrace:** 
```
wandb: Currently logged in as: kdelcastillo (use `wandb login --relogin` to force relogin)
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/icl-vae-v3xkFSzW/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 569, in init
    run = wi.init()
  File "/root/.local/share/virtualenvs/icl-vae-v3xkFSzW/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 416, in init
    run._set_run_obj(ret.run)
  File "/root/.local/share/virtualenvs/icl-vae-v3xkFSzW/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 623, in _set_run_obj
    c_dict = config_util.dict_no_value_from_proto_list(run_obj.config.update)
  File "/root/.local/share/virtualenvs/icl-vae-v3xkFSzW/lib/python3.8/site-packages/wandb/sdk/lib/config_util.py", line 30, in dict_no_value_from_proto_list
    d[item.key] = json.loads(item.value_json)["value"]
TypeError: 'int' object is not subscriptable
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/icl-vae-v3xkFSzW/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 569, in init
    run = wi.init()
  File "/root/.local/share/virtualenvs/icl-vae-v3xkFSzW/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 416, in init
    run._set_run_obj(ret.run)
  File "/root/.local/share/virtualenvs/icl-vae-v3xkFSzW/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 623, in _set_run_obj
    c_dict = config_util.dict_no_value_from_proto_list(run_obj.config.update)
  File "/root/.local/share/virtualenvs/icl-vae-v3xkFSzW/lib/python3.8/site-packages/wandb/sdk/lib/config_util.py", line 30, in dict_no_value_from_proto_list
    d[item.key] = json.loads(item.value_json)["value"]
TypeError: 'int' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/main.py", line 56, in <module>
    wandb.init(project='icl-vae', 
  File "/root/.local/share/virtualenvs/icl-vae-v3xkFSzW/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 606, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem
```

**Comment by quebin31** [comment] 2020-11-11 18:32
**Update:** I think I found the culprit, here:

https://github.com/wandb/client/blob/788b24639343d6bc7514aa9d33c4d7b56e73a780/wandb/sdk/wandb_run.py#L617-L623

https://github.com/wandb/client/blob/788b24639343d6bc7514aa9d33c4d7b56e73a780/wandb/sdk/lib/config_util.py#L27-L31

When I try to resume a run the API seems to be downloading the stored config for it, but the `run_obj.config.update` seems to have an extra key `wandb_version` with doesn't follow the schema that `config_util.dict_no_value_from_proto_list` is expecting:

```
[key: "base"
value_json: "{\"desc\": null, \"value\": {\"epochs\": 200, \"batch_size\": 32, \"decay_rate\": 0.95, \"lambda_cos\": 15, \"lambda_reg\": 0, \"lambda_vae\": 1, \"decay_every\": 0, \"learning_rate\": 5e-06}}"
, key: "incr"
value_json: "{\"desc\": null, \"value\": {\"epochs\": 100, \"batch_size\": 32, \"decay_rate\": 1, \"lambda_cos\": 15, \"lambda_reg\": 10, \"lambda_vae\": 1, \"decay_every\": 0, \"learning_rate\": 5e-06}}"
, key: "seed"
value_json: "{\"desc\": null, \"value\": 15}"
, key: "_wandb"
value_json: "{\"desc\": null, \"value\": {\"cli_version\": \"0.10.10\", \"python_version\": \"3.8.0\", \"is_jupyter_run\": false, \"is_kaggle_kernel\": false, \"framework\": \"torch\"}}"
, key: "log_interval"
value_json: "{\"desc\": null, \"value\": 50}"
, key: "wandb_version"
value_json: "1"
]
```

**Comment by vanpelt** [comment] 2020-11-11 19:02
Hey @quebin31 are you reading the wandb generated `config.yaml` in your example with `args.config`?  We automatically populate config on resume, and will always load a file named `config-defaults.yaml` if it exists.  You should never need to manually load our YAML.

If you can share a little more about what's inside of `args.config` and what you're trying to accomplish we can get you sorted.

**Comment by quebin31** [comment] 2020-11-11 19:10
> Hey @quebin31 are you reading the wandb generated `config.yaml` in your example with `args.config`?  We automatically populate config on resume, and will always load a file named `config-defaults.yaml` if it exists.  You should never need to manually load our YAML.
> 
> If you can share a little more about what's inside of `args.config` and what you're trying to accomplish we can get you sorted.

Thanks for the help, I'm not reading the generated `wandb` config, my script works in two ways:

1. Receives a path on  `args.config` with my own values (like epochs, seed, etc) when training.
2. Doesn't receive anything on `args.config`, therefore its value is `None` and uses an `id` and resumes an old run.

**Comment by quebin31** [comment] 2020-11-11 21:49
I've also noticed that `config.yaml` generated by `wandb` when resuming the run contains the `wandb_version` twice, note that I'm not touching this file at all.

**Comment by vanpelt** [comment] 2020-11-11 22:36
Yep, this definitely looks like a bug.  We'll get a fix out in the next release.

**Comment by vanpelt** [comment] 2020-11-12 05:04
Hey @quebin31 I just attempted to reproduce this and was unable to.  Here's is my simple script:

```python
import wandb
import time
import sys

if len(sys.argv) > 1:
   print("Setting new config")
   config = {"foo": 1, "bar": 2}
else:
   config = {}

wandb.init(project="resume", resume=True, allow_val_change=True)
print("Resumed config: ", dict(wandb.config))
wandb.config.update(config)

for i in range(10):
   wandb.log({"range": i})
   time.sleep(1)
```

You can run this file without any arguments and hit CTRL+C after a second or two.  Then run it with `python resume.py update` to have it mock the updating of the config.  I'm mystified how your config object ended up with `wandb_version` in the top level of your config.  Can you link me to a run and potentially send me a small script that reproduces this for you on a new run?

**Comment by quebin31** [comment] 2020-11-12 13:01
When I start a fresh new run, the `config.yaml` inside the run directory is just fine, the problem occurs when I try to resume a run from the cloud using an `id` and `resume = 'must'`. In my case, I tried this on another machine and the run just seems to resume normally, and the downloaded `config.yaml` is just okay.

**Comment by vanpelt** [comment] 2020-11-12 18:12
So strange, if you see this again, or can provide a reproducable piece of code we can ensure this double `wandb_version` issue never happens.

**Comment by ariG23498** [comment] 2020-12-08 05:08
Hey @quebin31 
Did you happen to find a solution to the ticket?
The ticket is going stale and it would be great if you could let us know about any persisting errors :smile:

**Comment by quebin31** [comment] 2020-12-08 05:10
It didn't happen again, so I guess it's already fixed.

**Comment by ariG23498** [comment] 2020-12-08 05:19
Thanks for the reply
Closing this issue :+1:

**Closed by ariG23498** 2020-12-08 05:19 UTC
Labels: bug
