### ISSUE TITLE
GraphQL-related server error when starting an agent for a sweep with prior runs

### ISSUE THREAD

**Issue by alexmirrington** [wandb/client#1349] opened 2020-10-11 12:44 UTC
**System:**

- OS: `Arch Linux x86_64`
- Kernel: `5.8.14-arch1-1`
- Python: `3.8.6`
- wandb: `0.10.4` for agent, multiple for prior runs.

**Description:**

When starting an agent from the CLI for a sweep with prior runs (created from the dashboard), a GraphQL error is raised. The error only seems to occur when these runs are standalone runs, _i.e._ not from another sweep.

**Steps to reproduce:**

1. Create a sweep in the `wandb` web UI
2. Select `Select prior runs`, and choose a single run that is not from a sweep. The runs I tried to select were logged using `wandb` CLI versions in the range `0.9.7 - 0.10.4`
3. Copy the command for starting an agent and run it in your terminal. The agent should error 3 times and terminate, each time producing a server error that seemed to stem from a GraphQL query.

Unfortunately, I have lost the stack trace from this bug as my 3 AM brain just wanted to get a sweep running, so please let me know if you manage to reproduce the issue.

**Comment by tyomhak** [comment] 2020-10-12 16:49
Hey @alexmirrington , thanks for reporting! Trying to reproduce this. Will keep you updated.

**Comment by annirudh** [comment] 2020-10-19 22:02
I think this issue is the same as: https://github.com/wandb/client/issues/1344.

@alexmirrington Could you please confirm whether or not you're still seeing the issue? We pushed a fix last week that should hopefully address this problem.

**Comment by ariG23498** [comment] 2020-12-16 12:56
Hey @alexmirrington 
We are closing this issue due to the inactivity. Please feel free to reopen if the issue still persists. :smile:

**Closed by ariG23498** 2020-12-16 12:56 UTC
Labels: bug
