### ISSUE TITLE
Experiment wont log unless wandb.init called every time you log

### ISSUE THREAD

**Issue by lisadunlap** [wandb/client#957] opened 2020-04-07 23:19 UTC
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.31
* Python version: 3.6
* Operating System: Mac

### Description

I am running some hyper parameter tuning experiments with a run for each configuration. I also have a run which tracks some experiment level metrics of how each configuration compares to others etc. However, when I try to log the experiment level metrics, nothing shows up for that run on my dashboard, even if I try to log it to a separate project. If I dont have runs for each configuration or if I call wandb.init before each call to wandb.log then it does show up, but that increases the latency significantly. 

### What I Did

```
class CloudExecutor(RayTrialExecutor):

    def __init__(self,
                 queue_trials=False,
                 reuse_actors=False,
                 ray_auto_init=False,
                 refresh_period=RESOURCE_REFRESH_PERIOD,
                 name="Executor",
                 use_wandb=False):
        super(CloudExecutor, self).__init__(queue_trials, reuse_actors, ray_auto_init, refresh_period)
        self._use_wandb = use_wandb
        self._name = name
        self._step = 0
        if use_wandb:
            wandb.init(project=self._name, name="executor", reinit=True, resume=True)

    def on_step_begin(self, trial_runner):
        """Before step() called, update the available resources."""
        self._update_avail_resources()
        if self._use_wandb and len(trial_runner.get_trials())>0:
            self.log_wandb(trial_runner)
        self._step += 1

    def log_wandb(self, trial_runner):
        """ Log experiment level metrics for trials on result
            WARNING: currently only works for sequential due to toal timesteps
        """
        if len(trial_runner.get_trials()) == 0:
            metric_val = 0
        elif trial_runner.scheduler_alg._mode == "max":
            metric_val = max([t.last_result.get(trial_runner.scheduler_alg._metric, -np.inf)
                       for t in trial_runner.get_trials()])
        else:
            metric_val = min([t.last_result.get(trial_runner.scheduler_alg._metric, np.inf)
                       for t in trial_runner.get_trials()])
        min_iteration = max([t.last_result.get("training_iteration", 0)
                             for t in trial_runner.get_trials()])
        if metric_val != -np.inf and metric_val != np.inf:
                wandb.init(project=self._name, name="executor",
                           id="executor", resume="executor", reinit=True)
                wandb.log({
                    "top_" + trial_runner.scheduler_alg._metric: metric_val,
                    "num_trials": len([t for t in trial_runner.get_trials() if t.status == Trial.RUNNING])
                }, step=min_iteration, commit = False)
            wandb.join()
```

**Comment by vanpelt** [comment] 2020-04-07 23:41
Hey @lisadunlap, you should only call wandb.init once per python process.  Also, the id must be different for each experiment.  You should only use the same id if you're resuming a previous experiment.

By specifying `commit=False` this means the data will not be logged to W&B until the process finishes or another call to log occurs.  

Calling wandb.log will flush metrics to disk so if there are lot of them it may slow down training.  To have the flushing happen asynchronously you can specify `sync=False` to your call to wandb.log.

I'm not familiar with the TrialExecutor.  I think the issue you're seeing is caused by the `commit=False` argument.  Removing it and the second call to wandb.init should make things work.  Please attach the debug.log if you're still seeing it not work.

**Comment by lisadunlap** [comment] 2020-04-08 01:08
No dice :( TrialExecutor is a class that handles the execution of trials, which are different hyper parameter configurations. 
[debug.log](https://github.com/wandb/client/files/4447672/debug.log)

**Comment by vanpelt** [comment] 2020-04-08 01:37
I believe what's happening is you're not calling wandb.init in the same process that is actually doing the training.  I would try printing `os.pid` in different places in the code to see what's going on.  You need to call `wandb.init` in the same python process as the one calling wandb.log.  Perhaps you could instrument whatever is returned from `get_trainable_cls`.

**Comment by lisadunlap** [comment] 2020-04-09 02:21
Thank you for the quick reply! I printed out the process ids and they do match in the places where I call init and where I call log. One thing that I forgot to mention though is that I commonly get these two errors:
`ERROR Error while calling W&B API: Error 1213: Deadlock found when trying to get lock; try restarting transaction (<Response [500]>)`
and
`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/files/lisadunlap/ccb_lsa_ucb_04-09_02-14-20/3n1tldai/file_stream`

The Client Error is for the run that is not logging anything. I also tried to remove the special characters from the project name but the error is still there.

**Comment by cvphelps** [comment] 2020-04-17 17:30
Thanks for the additional info Lisa! @raubitsj is going to take a look.

**Comment by zkx741481546** [comment] 2020-04-26 09:58
> 感谢您的附加信息丽莎！@raubitsj要去看看
similar problem here, `2020-04-26 17:47:56,938 ERROR   Thread-21 :20672 [internal.py:execute():113] 400 response executing GraphQL.
2020-04-26 17:47:56,938 ERROR   Thread-21 :20672 [internal.py:execute():114] {"errors":[{"message":"entityName required for project query","path":["project"]}],"data":{"project":null}}
2020-04-26 17:47:56,938 ERROR   Thread-21 :20672 [run_manager.py:check_status():469] Failed to check stop requested status: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql
Traceback (most recent call last):
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\apis\__init__.py", line 60, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\apis\internal.py", line 643, in check_stop_requested
    'projectName': project_name, 'entityName': entity_name, 'runId': run_id,
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\retry.py", line 95, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\apis\internal.py", line 116, in execute
    six.reraise(*sys.exc_info())
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\six.py", line 696, in reraise
    raise value
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\apis\internal.py", line 110, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\gql\transport\requests.py", line 39, in execute
    request.raise_for_status()
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\run_manager.py", line 467, in check_status
    run_id=self._run.id)
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\apis\__init__.py", line 62, in wrapper
    raise CommError(err.response, err)
wandb.apis.CommError: <Response [400]>
2020-04-26 17:47:57,342 INFO    MainThread:20672 [run_manager.py:_sync_etc():1295] received message from user process: {"save_policy": {"glob": "act_fun-relu_net_arch-vf-64_64_pi-64_64_l2_scale-0.01_agent_state-True_episode-50000_EP_LEN-750_n_training_envs-1_GPU-0_save_freq-15000_eval_freq-15000", "policy": "live"}}
2020-04-26 17:47:57,342 INFO    MainThread:20672 [run_manager.py:_sync_etc():1295] received message from user process: {"save_policy": {"glob": "events.out.tfevents.1587894477.PC", "policy": "live"}}
Name': entity_name, 'runId': run_id,
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\retry.py", line 95, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\apis\internal.py", line 116, in execute
    six.reraise(*sys.exc_info())
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\six.py", line 696, in reraise
    raise value
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\apis\internal.py", line 110, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\gql\transport\requests.py", line 39, in execute
    request.raise_for_status()
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\run_manager.py", line 467, in check_status
    run_id=self._run.id)
  File "C:\Users\zkx74\Anaconda3\lib\site-packages\wandb\apis\__init__.py", line 62, in wrapper
    raise CommError(err.response, err)
wandb.apis.CommError: <Response [400]>
2020-04-26 17:47:57,342 INFO    MainThread:20672 [ziaz7pye:run_manager.py:_sync_etc():1295] received message from user process: {"save_policy": {"glob": "act_fun-relu_net_arch-vf-64_64_pi-64_64_l2_scale-0.01_agent_state-True_episode-50000_EP_LEN-750_n_training_envs-1_GPU-0_save_freq-15000_eval_freq-15000", "policy": "live"}}
2020-04-26 17:47:57,342 INFO    MainThread:20672 [ziaz7pye:run_manager.py:_sync_etc():1295] received message from user process: {"save_policy": {"glob": "events.out.tfevents.1587894477.PC", "policy": "live"}}
`

**Comment by ariG23498** [comment] 2020-12-03 06:34
Hey folks
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Closed by ariG23498** 2020-12-03 06:34 UTC
Labels: c:cling
