### ISSUE TITLE
SIGINT handling when used with PyTorch Lightning.

### ISSUE THREAD

**Issue by yukw777** [wandb/client#1173] opened 2020-07-23 21:05 UTC
`wandb --version && python --version && uname`

* Weights and Biases version: 0.9.3
* Python version: 3.8.2
* Operating System: Darwin

### Description

I'm using PyTorch Lightning with WandB. PyTorch Lightning's training loop catches SIGINT (and others) and gracefully shuts off, allowing the script to continue its execution. This is quite useful b/c you can stop your training in the middle and still run the test loop and other tasks after. However, when I use WandB with PyTorch Lightning, it seems like WandB catches SIGINT correctly and passes it down to the script, thus stopping the execution of the script, but it also kills the script right there, so the test loop and other tasks do not get executed. Is there a workaround?

**Comment by cvphelps** [comment] 2020-07-24 22:13
Thanks for reporting. @borisdayma could you take a look?

**Comment by cvphelps** [comment] 2020-07-24 23:52
Hi there, Boris suggests that you try the new version of our client. @raubitsj what would be the recommended way for @yukw777 to try the new CLI?

**Comment by raubitsj** [comment] 2020-07-25 01:53
The new version of the client is available by running the following command:
```
pip install --upgrade --pre wandb
```

**Comment by yukw777** [comment] 2020-07-27 17:54
with the pre-release (0.10.0rc1) I see this error:
```
Traceback (most recent call last):                                    
  File "/Users/peteryu/leela-zero-pytorch/leela_zero_pytorch/train.py", line 25, in main
    trainer.fit(
  File "/Users/peteryu/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 1097, in fit
    results = self.accelerator_backend.train(model)
  File "/Users/peteryu/pytorch-lightning/pytorch_lightning/accelerator_backends/cpu_backend.py", line 41, in train
    results = self.trainer.run_pretrain_routine(model)
  File "/Users/peteryu/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 1230, in run_pretrain_routine
    self.train()
  File "/Users/peteryu/pytorch-lightning/pytorch_lightning/trainer/training_loop.py", line 359, in train
    self.on_train_start()
  File "/Users/peteryu/pytorch-lightning/pytorch_lightning/trainer/callback_hook.py", line 97, in on_train_start
    callback.on_train_start(self, self.get_model())
  File "/Users/peteryu/pytorch-lightning/pytorch_lightning/utilities/distributed.py", line 12, in wrapped_fn
    return fn(*args, **kwargs)
  File "/Users/peteryu/pytorch-lightning/pytorch_lightning/callbacks/model_checkpoint.py", line 252, in on_train_start
    ckpt_path = os.path.join(
  File "/Users/peteryu/.pyenv/versions/3.8.2/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Users/peteryu/.pyenv/versions/3.8.2/lib/python3.8/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```

The issue persists on 0.9.4.

**Comment by vanpelt** [comment] 2020-07-27 22:30
Hey @yukw777 the error looks to be in pytorch lightning itself [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/model_checkpoint.py#L256).  Are you specifying `save_dir` or `log_model=True` in your instance of WandbLogger?  It might also be caused by not having a name for the logger, I would also try passing `name` to the WandbLogger.  Looking at the code it's either a nil `save_dir` which will get set if `log_model=True` or if it's passed in, or it's a nil name which should get set to the wandb project name but may not always [get set](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/loggers/wandb.py#L144).

**Comment by yukw777** [comment] 2020-07-28 15:43
@vanpelt I've tried two combinations: (pl==0.8.5, wandb==0.9.4) and (pl==0.8.5, wandb==0.10.0rc1) both without setting `save_dir`, `log_model` or `name` (basically all the default values for `WandbLogger`). I only see the error I posted above with `0.10.0rc1`, which suggests to me that the behavior has changed on the wandb side. I think it's b/c `wandb.init()` no longer generates a project name automatically if `name=None` on `0.10.0rc1`.

**Comment by yukw777** [comment] 2020-07-28 15:45
I just tried again with (pl==0.8.5, wandb==0.10.0rc1) (this time I manually set the name parameter to get around the error I posted above), and the issue still persists.

**Comment by yukw777** [comment] 2020-07-28 16:17
Alright, upon further investigation, this is what I've found:

1. The SIGINT handling issue is indeed fixed in 0.10.0rc1!
1. `run.project_name()` always returns `None` on 0.10.0rc1. On 0.9.4 and 0.9.3, it was autogenerated if not set.

**Comment by vanpelt** [comment] 2020-07-28 19:32
Thanks for this analysis!  We'll fix the project_name issue ASAP.

**Comment by raubitsj** [comment] 2020-07-29 20:26
run.project_name() is fixed in 0.10.0rc2

Install update with:
pip install --upgrade --pre wandb

**Comment by yukw777** [comment] 2020-08-24 02:31
@raubitsj Thanks! I'll file an issue on the github.com/wandb/client-ng side. I was wondering where the RCs were being tagged haha

**Comment by ariG23498** [comment] 2020-12-04 13:02
Hey @yukw777 
In the past few months we've majorly reworked the CLI and UI for Weights & Biases. We're closing inactivate threads for the time being. Please comment to reopen. :smile:

**Closed by ariG23498** 2020-12-04 13:02 UTC
Labels: c:cling-fixed
