### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items' in wandb_config.

### ISSUE THREAD

**Issue by kushalarora** [wandb/client#724] opened 2019-12-18 17:57 UTC
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.18
* Python version: 3.7
* Operating System: Linux

### Description
My wandb run randomly crashes for a few runs (Traceback included). This doesn't happen all the time but randomly like 1 out of 3 time a script is run. If this helps, I am running my code on compute nodes which do not have access to internet. I plan to save my run logs locally and run `wandb sync` from login nodes which have access to internet to sync them online. 

### TRACE

wandb: Tracking run with wandb version 0.8.18
Traceback (most recent call last):
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/site-packages/wandb/internal_cli.py", line 106, in <module>
    main()
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/site-packages/wandb/internal_cli.py", line 98, in main
    headless(args)
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/site-packages/wandb/internal_cli.py", line 54, in headless
    util.sentry_reraise(e)
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/site-packages/wandb/util.py", line 92, in sentry_reraise
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/site-packages/wandb/internal_cli.py", line 36, in headless
    run = wandb.wandb_run.Run.from_environment_or_defaults()
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/site-packages/wandb/wandb_run.py", line 247, in from_environment_or_defaults
    config = Config.from_environment_or_defaults()
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/site-packages/wandb/wandb_config.py", line 87, in from_environment_or_defaults
    return Config(config_paths=conf_paths, wandb_dir=wandb.wandb_dir(), run_dir=run_dir)
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/site-packages/wandb/wandb_config.py", line 54, in __init__
    self.set_run_dir(run_dir)
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/site-packages/wandb/wandb_config.py", line 181, in set_run_dir
    self._load_values()
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/site-packages/wandb/wandb_config.py", line 151, in _load_values
    self._load_file(path)
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/site-packages/wandb/wandb_config.py", line 134, in _load_file
    for key, val in loaded.items():
AttributeError: 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
  File "experiments/natural_language/dataset_experiments.py", line 36, in <module>
    is_natural_lang_exp=True)
  File "/lustre03/project/6008064/karora/quant_exp_bias/experiments/util.py", line 62, in initialize_experiments
    sync_tensorboard=False)
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/site-packages/wandb/__init__.py", line 1067, in init
    _init_headless(run)
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/site-packages/wandb/__init__.py", line 277, in _init_headless
    success, _ = server.listen(30)
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/site-packages/wandb/wandb_socket.py", line 46, in listen
    self.connect()
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/site-packages/wandb/wandb_socket.py", line 40, in connect
    self.connection, addr = self.socket.accept()
  File "/home/karora/miniconda3/envs/quant_exp/lib/python3.7/socket.py", line 212, in accept
    fd, addr = self._accept()
socket.timeout: timed out
(END)

**Comment by vanpelt** [comment] 2019-12-18 20:17
This might be caused by large git api calls that are timing out.  Can you try running with `WANDB_DISABLE_CODE=true`

**Comment by kushalarora** [comment] 2019-12-20 20:12
Thanks @vanpelt .

 I'll try it out.

I just wanted to ascertain that AttributeError is happening due to socket timing out.

**Comment by vanpelt** [comment] 2019-12-20 23:03
Yeah, the error is really mis leading.  I'll look into the attributeerror bug, but I think the root cause is something else.

**Comment by ariG23498** [comment] 2020-12-03 04:46
Hey @kushalarora 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Closed by ariG23498** 2020-12-03 04:46 UTC
Labels: bug
