### ISSUE TITLE
wandb.errors.Error: wandb[sweeps] is required to use the local controller. Please run `pip install wandb[sweeps]`.[CLI]: 

### ISSUE THREAD

**Issue by bolongliu** [wandb/client#3476] opened 2022-04-05 18:49 UTC
### Describe the bug

```python 
# The simplest way to run a controller:
sweep = wandb.controller(sweep_id)
sweep.run()
```

```shell
wandb.errors.Error: wandb[sweeps] is required to use the local controller. Please run `pip install wandb[sweeps]`.
```

### Environment

WandB version:version 0.12.11

OS:ubuntu

Python version:3.8

Versions of relevant libraries:

**Comment by ramit-wandb** [comment] 2022-04-05 19:20
Hi @bolongliu,

In order to use the local controller, you must install `wandb[sweeps]`, since the local controller is not available in the `wandb` package by default.

This should be possible with

```
pip install wandb[sweeps]
```

Are there any issues you are seeing when trying to install this? Please let us know how we can help further here.

Thanks,
Ramit

**Comment by ramit-wandb** [comment] 2022-04-11 19:02
​Hi @bolongliu,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

Best,
Weights & Biases
​

**Comment by guoxyer** [comment] 2022-04-13 18:05
Hi @ramit-wandb ,
I have the same issue on Mac OS, python3, wandb: ver 0.12.14, pip 22.0.4

after 'pip install wandb[sweeps]'
I got 'zsh: no matches found: wandb[sweeps]'

Thanks,
Guoxy

**Comment by kptkin** [comment] 2022-04-13 18:34
@guoxyer This is `zsh`/`pip` issue. To make this command work you need to add `""`:
```
pip install "wandb[sweeps]"
``` 
should do the trick... hope it helps

**Comment by ramit-wandb** [comment] 2022-04-13 18:34
Ah, this issue is likely coming from zsh trying to parse the rectangular brackets. Could you try the following sequence of commands:

```
$ bash
$ pip install wandb[sweeps]
$ zsh
```

Thanks,
Ramit

**Comment by guoxyer** [comment] 2022-04-13 19:23
Hi @kptkin , @ramit-wandb 
Thanks for your help, the issue is resolved.
I tried both, all works well.

Thanks,
Guoxy

**Comment by ramit-wandb** [comment] 2022-04-14 23:49
Of course! Closing this issue out in that case. Please let us know if there are any other concerns and we can continue this conversation.

**Closed by ramit-wandb** 2022-04-14 23:49 UTC
Labels: cli
