### ISSUE TITLE
Images: logging an image that is already saved to the wandb directory doesn't resize properly

### ISSUE THREAD

**Issue by maria-korosteleva** [wandb/client#1128] opened 2020-07-01 02:56 UTC
`wandb --version && python --version && uname`

* Weights and Biases version: 0.9.1
* Python version: 3.6
* Operating System: Win 10

### Description

I'm logging png images to wandb run with wandb.log(). The overall process seems to go fine, but only a part of each image is displayed in web-interface (Media charts): they seem to have been cropped to a square size somewhere on the way.
Is there a way to view whole images?

### What I Did

```
wandb.log({'image': wb.Image('predicted.png')}, step=log_step)
```

**Comment by vanpelt** [comment] 2020-07-02 16:46
Hey @maria-korosteleva we shouldn't be cropping images.  Can you link to an example run that's been affected.  Also if you can provide a sample image that you're trying to log that would help us reproduce.

**Comment by maria-korosteleva** [comment] 2020-07-03 01:07
Sure
This the view on the dashboard: https://app.wandb.ai/maria_korosteleva/Test-Garments-Reconstruction/runs/4d9v8l8x?workspace=user-maria_korosteleva

This is how I expect the image to be shown: https://app.wandb.ai/maria_korosteleva/Test-Garments-Reconstruction/runs/4d9v8l8x/files/intermediate_preds/skirt_4_panels_WZFFG4GTDC/skirt_4_panels_WZFFG4GTDC_predicted__pattern.png

**Comment by vanpelt** [comment] 2020-07-03 19:59
Hey Maria, how are you passing the images to `wandb.log`.  Looking at your project, I see the files are being stored in `intermediate_preds`.  We automatically do some pre-processing and store images in `/media/images` when you're passing raw data to `wandb.Image`.  If you pass a path to `wandb.Image` we do that preprocessing if the path is outside of the current `wandb.run.dir`.  I imagine you're passing  a pass directly to `wandb.Image` that already lives in `wandb.run.dir`?  If you can share some sample code, we can reproduce and figure out the best solution.

**Comment by maria-korosteleva** [comment] 2020-07-06 01:26
Yes, you are right, I use an image that is already in the `wandb.run.dir` (sorry, I guess, I oversimplified the original example)

There is one thing I noticed that might be helpful: it looks like the cropping problem is happening purely in the web-page interface. When I right-click on the image and then "Open image in new tab", it shows the full image

If I look at the page code, I can see the block wrapping image do the wrong thing
![image](https://user-images.githubusercontent.com/6837635/86547100-ba3da300-bf72-11ea-84d0-0c5287c2bf23.png)

 Looking at this, I don't think it's connected with the way I pass the image to `wandb.log` but let me know if you still need that code snippet

**Comment by vanpelt** [comment] 2020-07-06 16:14
Hey @maria-korosteleva the sizing error is because of the image already being in the run directory.  We'll look into a fix for this case, but until then if you either pass raw data or a path from outside of wandb.run.dir to `wandb.Image` it should work.

**Comment by maria-korosteleva** [comment] 2020-07-07 01:54
Great, thank you for the tip!

вт, 7 июл. 2020 г. в 01:15, Chris Van Pelt <notifications@github.com>:

**Comment by maria-korosteleva** [comment] 2020-07-09 07:28
Hi @vanpelt
I have tried your suggestion to log image with the path from outside the run directory (to `./wandb/intermediate_preds/` to be specific, while run dirs are in `./wandb/<run_dir_name>`) 

In the web-interface, I can see that logged images are copied to `/media/images` (so they should have gone through the pre-processing step that you mentioned). But _the visualization is still cropped_ though, and only the square piece of the original image is displayed on the dashboard

Here is the run dashboard: 
https://app.wandb.ai/maria_korosteleva/Test-Garments-Reconstruction/runs/3tvus7li?workspace=user-maria_korosteleva

Hope this helps to figure out the cause

**Comment by nbardy** [comment] 2020-07-10 00:55
@maria-korosteleva Thanks for reporting the bug. There was an issue with correctly picking up metadata. I've patched the client library so this won't happen in the future.

https://github.com/wandb/client/pull/1152

I'm also going to add a patch the UI to handle the images you've already logged without metadata so they get cropped to a square.

**Comment by maria-korosteleva** [comment] 2020-07-10 01:09
@nbardy thank you so much! Looking forward to the fix!

**Comment by ariG23498** [comment] 2020-12-04 05:53
Hey @maria-korosteleva 
In the past few months we've majorly reworked the CLI and UI for Weights & Biases. We're closing stale issues. Please comment to reopen. :smile:

**Closed by ariG23498** 2020-12-04 05:53 UTC
