### ISSUE TITLE
The order of parameters in sweep config will influence the result

### ISSUE THREAD

**Issue by possible1402** [wandb/client#2451] opened 2021-07-26 11:39 UTC
**Description**
I used the sweep example of pytorch version [https://colab.research.google.com/github/wandb/examples/blob/master/colabs/pytorch/Organizing_Hyperparameter_Sweeps_in_PyTorch_with_W%26B.ipynb#](url) and found that if I change the order of parameters, the corresponding will be different. For example, in this example, if the 'dropout' in parameters_dict is changing from [0.3, 0.4, 0.5] to [0.4,0.3,0.5], the results don't match.
![image](https://user-images.githubusercontent.com/29528469/126982643-7745b72f-06f2-46e5-bcae-f9e5f708ef25.png)

**Wandb features**
wandb.sweep()

**How to reproduce**
[https://colab.research.google.com/github/wandb/examples/blob/master/colabs/pytorch/Organizing_Hyperparameter_Sweeps_in_PyTorch_with_W%26B.ipynb#](url), I used grid search.

**Environment**
- Environment: Google Colab

**Comment by vanpelt** [comment] 2021-07-26 14:54
Closing as a duplicate of https://github.com/wandb/examples/issues/82

**Closed by vanpelt** 2021-07-26 14:54 UTC
Labels: cli
